/*
 *
 * eqwc.js -- build of Extended QGIS Web Client
 *
 * version: 1.8.3
 * buildDate: 2019-03-15
 *
 * Copyright (2014-2019), Level2, All rights reserved.
 * More information at https://github.com/uprel/gisapp
 *
 */
Array.prototype.forEach||(Array.prototype.forEach=function(a,b){var d,c;if(null==this)throw new TypeError("this is null or not defined");var e=Object(this),f=e.length>>>0;if("[object Function]"!=={}.toString.call(a))throw new TypeError(a+" is not a function");b&&(d=b);for(c=0;c<f;){var g;Object.prototype.hasOwnProperty.call(e,c)&&(g=e[c],a.call(d,g,c,e));c++}});null===projectData.search&&Eqwc.settings.search&&(projectData.search=Eqwc.settings.search);null===projectData.geoCode&&null===projectData.wsgi&&Eqwc.settings.geoCode&&(projectData.geoCode=Eqwc.settings.geoCode);null===projectData.wsgi&&null===projectData.geoCode&&Eqwc.settings.wsgi&&(projectData.wsgi=Eqwc.settings.wsgi);null===projectData.locationServices&&Eqwc.settings.locationServices&&(projectData.locationServices=Eqwc.settings.locationServices);Eqwc.common={};
Eqwc.common.createHyperlink=function(a,b,d){null==b&&(b=a);""!=a&&/^((http|https|ftp):\/\/).+\..+/i.test(a)&&(/\<a./i.test(a)||(a='<a class="link" href="'+a+'" target="_blank">'+b+"</a>"));""<d&&RegExp(d,"i").test(a)&&(a='<a href="/'+a+'" target="_blank">'+b+"</a>");return a};
Eqwc.common.manageFile=function(a,b){var d=!1;if(b){var c=a.split(".")[1].toLowerCase();if("jpg"==c||"jpeg"==c||"gif"==c||"png"==c)d=!0}c=window.location.origin;c=1==projectData.uploadDir.split(".").length?c+projectData.uploadDir:c+projectData.uploadDir.split(".")[1];return d?"<a target='_blank' href='"+c+a+"'><img src='"+c+"thumb/"+a+"'></a>":Eqwc.common.createHyperlink(c+a,a,null)};
Eqwc.common.getRasterFieldName=function(a,b){return Eqwc.settings.overWriteRasterFieldName&&Eqwc.settings.overWriteRasterFieldName[a]?Eqwc.settings.overWriteRasterFieldName[a][0]==b?Eqwc.settings.overWriteRasterFieldName[a][1]:b:b};Eqwc.common.layerFieldNameExists=function(a,b){for(var d=wmsLoader.layerProperties[a],c=0;c<d.attributes.length;c++)if(d.attributes[c].name==b)return!0;return!1};Eqwc.common.lookup=function(a,b,d){for(var c=0,e=a.length;c<e;c++)if(a[c]&&a[c][b]===d)return a[c]};
Eqwc.common.getIdentifyLayerName=function(a){var b=projectData.layers[a];if("undefined"==typeof b)return a;if(b.identifyname)return b.identifyname;b=b.layername;Eqwc.settings.replaceIdentifyLayerWithView&&-1<Eqwc.settings.replaceIdentifyLayerWithView.indexOf(b)&&Eqwc.common.getLayerId(b+"_view")&&(b+="_view");return projectData.layers[a].identifyname=b};
Eqwc.common.getIdentifyLayerNameRevert=function(a){var b;return-1<a.indexOf("_view")&&(b=a.split("_view")[0],Eqwc.settings.replaceIdentifyLayerWithView&&-1<Eqwc.settings.replaceIdentifyLayerWithView.indexOf(b))?b:a};Eqwc.common.getHiddenLayersFromSettings=function(){var a=[Eqwc.settings.QgisUsersPrintName],b=Eqwc.settings.replaceIdentifyLayerWithView;if(b)for(var d=0;d<b.length;d++){var c=Eqwc.common.getLayerId(b[d]);c&&(c=Eqwc.common.getIdentifyLayerName(c),b[d]!=c&&a.push(c))}return a};
Eqwc.common.getProjectUrl=function(){return projectData.gis_projects.path+projectData.project};Eqwc.common.getLayerId=function(a){for(var b in projectData.layers)if(projectData.layers[b].layername===a)return projectData.layers[b].id;return!1};
Eqwc.common.parseInputTextToCoord=function(a){var b=[],d=[];-1<a.indexOf(",")?d=a.split(","):-1<a.indexOf(";")?d=a.split(";"):-1<a.indexOf(" ")&&(d=a.split(" "));if(0==d.length)return!1;for(var c in d)isNaN(parseFloat(d[c]))||b.push(parseFloat(d[c]));return 0==b.length?!1:b};var UrlParams={useSSL:!1,url:"",baseUrl:"",params:{},parse:function(){var a="",a=document.documentURI?document.documentURI:window.location.href,a=a.replace(/\+/g," "),a=decodeURI(a);UrlParams.url=a;UrlParams.useSSL=UrlParams.url.match(/^https:/);a=a.split("?");UrlParams.baseUrl=a[0];if(1<a.length)for(var a=a[1].split("&"),b=0;b<a.length;b++){var d=a[b].split("=");UrlParams.params[decodeURIComponent(d[0])]=decodeURIComponent(d[1])}}};function Permalink(){this.openLogin=this.opacities=this.inactiveLayers=this.activeLayers=this.startZoom=this.startScale=this.startCenter=this.startExtent=this.initialOverlayTopics=this.initialBackgroundTopic=this.initialTopic=this.useTiledWMS=null}
Permalink.prototype={read:function(a,b){void 0!=a.tiledWms&&(this.useTiledWMS=1==a.tiledWms);void 0!=a.openLogin&&(this.openLogin="true"==a.openLogin);void 0!=a.topic&&(this.initialTopic=a.topic);void 0!=a.background&&(this.initialBackgroundTopic=a.background);void 0!=a.overlays&&(this.initialOverlayTopics=a.overlays.split(","));void 0!=a.extent&&(this.startExtent=$.map(a.extent.split(","),function(a,b){return parseFloat(a)}));void 0!=a.center&&(this.startCenter=$.map(a.center.split(","),function(a,
b){return parseFloat(a)}));void 0!=a.scale&&(this.startScale=parseFloat(a.scale));void 0!=a.zoom&&(this.startZoom=parseFloat(a.zoom));void 0!=a.activeLayers&&(this.activeLayers=a.activeLayers.split(","));void 0!=a.inactiveLayers&&(this.inactiveLayers=a.inactiveLayers.split(","));if(void 0!=a.opacities)try{this.opacities=$.parseJSON(a.opacities)}catch(d){alert("opacities:\n"+d)}void 0!=b&&b()},addOverlays:function(a,b){}};function Login(){}Login.prototype={status:function(a){a({success:!1,user:"User"})},signIn:function(a,b,d){d({success:!0,user:"User"})},signOut:function(a){a()}};function Search(){}Search.prototype={submit:function(a,b){},highlight:function(a,b){}};function Geocode(a,b,d,c,e){this.types=a;this.country=b;this.limit=d;this.provider=c;this.language=e}Geocode.prototype=new Search;Geocode.prototype.submit=function(a,b){var d=$.ajax({url:"admin/proxy.php",data:this.parseSearchParams(a),context:this});d.done(function(a,d){this.parseResults(a,d,b)});d.fail(function(a,b){alert(I18n.search.failed+"\n"+a.status+": "+a.statusText)})};
Geocode.prototype.parseSearchParams=function(a){a=$.trim(a);var b=Map.map.getView(),b=ol.proj.toLonLat(b.getCenter(),b.getProjection().getCode());return{limit:this.limit,types:this.types,country:this.country,language:this.lang,provider:this.provider,query:a,proximity:b[0]+","+b[1]}};
Geocode.prototype.parseResults=function(a,b,d){a=$.map(a.features,function(a,b){var d=a.place_name,g=new ol.geom.Point([a.geometry.coordinates[0],a.geometry.coordinates[1]]);g.transform("EPSG:4326",Map.map.getView().getProjection());var h=g.getExtent();return{name:d,bbox:h,point:g}});d([{category:null,results:a,total:a.length}])};function QgisPermalink(){}QgisPermalink.prototype=new Permalink;QgisPermalink.prototype.read=function(a,b){Permalink.prototype.read.call(this,a);void 0!=a.startExtent&&(this.startExtent=$.map(a.startExtent.split(","),function(a,b){return parseFloat(a)}));void 0!=a.visibleLayers&&(this.activeLayers=a.visibleLayers.split(","));b()};function WsgiSearch(a,b,d,c){this.url=a;this.geomUrl=b;this.showHighlightLabel=d;this.searchTables=c}WsgiSearch.prototype=new Search;WsgiSearch.prototype.submit=function(a,b){var d=$.ajax({url:this.url,data:{query:$.trim(a),searchtables:this.searchTables,srs:projectData.crs.split(":")[1]},dataType:"json",context:this});d.done(function(a,d){this.parseResults(a,d,b)});d.fail(function(a,b){alert(I18n.search.failed+"\n"+a.status+": "+a.statusText)})};
WsgiSearch.prototype.parseResults=function(a,b,d){b={};for(var c=null,e=0;e<a.results.length;e++){var f=a.results[e];null==f.bbox?(c=f.displaytext,void 0===b[c]&&(b[c]=[])):b[c].push({name:f.displaytext,highlight:{searchtable:f.searchtable,displaytext:f.displaytext,showlayer:f.showlayer},bbox:f.bbox})}a=$.map(b,function(a,b){return{category:b,results:a}});d(a)};
WsgiSearch.prototype.highlight=function(a,b){var d=$.ajax({url:this.geomUrl,data:{searchtable:a.searchtable,displaytext:a.displaytext,showlayer:a.showlayer,srs:projectData.crs.split(":")[1]},dataType:"text"}),c=Eqwc.common.getLayerId(a.showlayer);c&&(Map.layers[c].visible||Map.setLayerVisible(c,!0,!0));var e=this.showHighlightLabel;d.done(function(c,d){var h=(new ol.format.WKT({splitCollection:!0})).readFeatures(c);if(e&&null!=a.displaytext)for(var l in h){var m=a.displaytext.replace(/ \([^\)]+\)$/,
"");h[l].set("labelstring",m)}l=new ol.layer.Vector({source:new ol.source.Vector({features:h}),style:function(a,b){var c=new ol.style.Stroke({color:Eqwc.settings.symbolizersHighLightLayer.Line.strokeColor,width:Eqwc.settings.symbolizersHighLightLayer.Line.strokeWidth}),d=new ol.style.Fill({color:"rgba(255, 140, 0, 0)"}),e=null;a.get("labelstring")&&(e=new ol.style.Text({text:a.get("labelstring"),textAlign:"center",textBaseline:"bottom",offsetY:-5,font:"normal 16px Helvetica,Arial,sans-serif",fill:new ol.style.Fill({color:"rgba(0, 0, 0, 1.0)"}),
stroke:new ol.style.Stroke({color:"rgba(255, 255, 255, 1.0)",width:2})}));return[new ol.style.Style({image:new ol.style.Circle({radius:4,fill:d,stroke:c}),fill:d,stroke:c,text:e})]}});l.name="highlight";h=h[0].getGeometry().getExtent();Map.zoomToExtent(h,Config.map.minScaleDenom.search);b(l)})};var Config={parseExtentToArray:function(a){var b=[];a=a.split(",");b.push(parseInt(a[0]));b.push(parseInt(a[1]));b.push(parseInt(a[2]));b.push(parseInt(a[3]));return b},extractStringFromObject:function(a,b){if(!b)return null;if(-1==b.indexOf(a))return b;var d="",d=b.indexOf("(")+1,c=b.indexOf(")");return d="["+b.substring(d,c)+"]"},getLayerName:function(a){return projectData.layers[a]?projectData.use_ids?projectData.layers[a].layername:a:a},baseLayerExists:function(a){var b=projectData.baseLayers(),
d;for(d in b)if(b[d].title==a)return!0;return!1},extraLayerExists:function(a){var b=projectData.extraLayers(),d;for(d in b)if(b[d].title==a)return!0;return!1},debug:!1,gui:{hideShareButton:!0,hideLoginButton:!1,useLayertreeGroupCheckboxes:!0}};Config.login=new Login;Config.sslLogin=!1;Config.data={};Config.data.initialTopic=projectData.project;Config.defaultProperties={following:Eqwc.settings.mobileEnableTracking,orientation:!1,scalebar:!0};Config.featureInfo={};Config.featureInfo.format="text/xml";
Config.featureInfo.useWMSGetFeatureInfo=!0;Config.featureInfo.wmsMaxFeatures=Eqwc.settings.limitSearchMaxResults?Eqwc.settings.limitSearchMaxResults:null;
Config.featureInfo.tolerances={point:Eqwc.settings.featureInfoTolerances&&Eqwc.settings.featureInfoTolerances.point?Eqwc.settings.featureInfoTolerances.point:4,line:Eqwc.settings.featureInfoTolerances&&Eqwc.settings.featureInfoTolerances.line?Eqwc.settings.featureInfoTolerances.line:4,polygon:Eqwc.settings.featureInfoTolerances&&Eqwc.settings.featureInfoTolerances.polygon?Eqwc.settings.featureInfoTolerances.polygon:2};Config.map={};Config.map.dpi=96;Config.map.extent=Config.parseExtentToArray(projectData.extent);
Config.map.init={center:ol.extent.getCenter(Config.map.extent),zoom:6};""==projectData.crs&&(alert("Map CRS must be set in QGIS!"),Eqwc.settings.useGisPortal?window.location.href=Eqwc.settings.gisPortalRoot:window.location.href="/");Config.map.projectionList=[];Config.map.projectionList.push([projectData.crs,projectData.crs_description]);
if(void 0===proj4.defs[projectData.crs]){proj4.defs(projectData.crs,projectData.proj4);var projDef=CustomProj[projectData.crs];Config.map.projection=new ol.proj.Projection({code:projectData.crs,extent:projDef.extent,units:projDef.units,axisOrientation:!1===projDef.yx?"enu":"neu"})}else Config.map.projection=ol.proj.get(projectData.crs);
for(var j=0;j<projectData.crs_list.length;j++){var code=projectData.crs_list[j];void 0===proj4.defs[code]&&proj4.defs(code,Proj4js.defs[code]);var title=proj4.defs[code].title?proj4.defs[code].title:code;code!=projectData.crs&&Config.map.projectionList.push([code,title])}Config.map.viewOptions={projection:Config.map.projection,extent:projectData.restrictToStartExtent?Config.map.extent:void 0};Config.data.baselayers=[];
if(null!==projectData.baseLayers())for(var i=0;i<projectData.baseLayers().length;i++){var bl=projectData.baseLayers()[i];"Google"!=bl.type&&Config.data.baselayers.push(bl);"WMTS"==bl.type&&(Config.map.viewOptions.resolutions=$.parseJSON(bl.definition).resolutions)}Config.data.extralayers=projectData.extraLayers();Config.data.wfslayers={};Config.data.gotolayers={};Config.map.wmsServerType="qgis";
Config.map.wmsParams={FORMAT:"image/png; mode=8bit",TRANSPARENT:null==projectData.baseLayers()&&null==projectData.extraLayers()?!1:!0};Config.map.useTiledBackgroundWMS=!0;Config.map.useTiledOverlayWMS=!1;Config.map.minScaleDenom={map:5E3,geolocation:null,search:5E3};Config.map.initialGeolocationMaxScale=2E3;var sCon=projectData.geoCode?projectData.geoCode:null;null!=sCon&&(Config.search=new Geocode(sCon.layers,sCon.country,10,sCon.provider,projectData.lang));
null==sCon&&projectData.wsgi&&(Config.search=new WsgiSearch("/wsgi/search.wsgi","/wsgi/getSearchGeom.wsgi",!1,projectData.wsgi.searchtables));Config.mapfishSearchUrl=function(a){return"data/mapfish_search_response.json"};Config.mapfishParseFeature=function(a){return{category:a.kategorie,name:a.begriff,highlight:{fid:a.fid,layer:"FullSearch"+a.kategorie},bbox:[a.bbox_xmin,a.bbox_ymin,a.bbox_xmax,a.bbox_ymax]}};Config.mapfishHighlightWmsUrl="/wms/FullSearch";Config.permalink=new Permalink;
Config.mapfishLocateUrl=function(a,b){return"/locate/"+a+"?"+$.param({locations:b})};Config.print={hires:!1,dpi:300};Config.customInitViewer=function(){};var Map={topics:{},topic:null,layers:{},backgroundTopic:null,backgroundLayers:{},map:null,minResolution:null,topicLayer:null,backgroundLayer:null,selectionLayer:null,redliningLayer:null,highlightLayer:null,geolocationLayer:null,overlayLayers:{},geolocation:null,deviceOrientation:null,windowOrientation:void 0,scaleLine:null,lastClickPos:null,clickMarker:null,ignoreClick:!1,singleClickHandlers:{}};Map.useTiledWMS=Eqwc.settings.mobileUseTiledWMS;Map.userCrs=null;
Map.userCrsTitle=function(){return Config.map.projectionList.filter(function(a){return a[0]==Map.userCrs})[0][1]};
Map.createMap=function(){null!=Config.permalink.useTiledWMS&&(Map.useTiledWMS=Config.permalink.useTiledWMS);Map.map=new ol.Map({layers:[],target:"map",view:new ol.View(Config.map.viewOptions),controls:[]});Map.map.getView().fit(Config.map.extent,Map.map.getSize());Map.map.getView().on("change:rotation",function(){$.event.trigger({type:"maprotation",rotation:Map.map.getView().getRotation()})});Map.setMinScaleDenom(Config.map.minScaleDenom.map);Map.map.getView().on("change:resolution",function(){Map.map.getView().getResolution()<
Map.minResolution&&Map.map.getView().setResolution(Map.minResolution)});Map.map.on("singleclick",function(a){if(!Map.ignoreClick){Map.lastClickPos=a.coordinate;for(var b in Map.singleClickHandlers){var d=Map.singleClickHandlers[b];d.isActive()&&d.handleEvent(a)}}})};
Map.clearLayers=function(){Map.map.getLayers().clear();Map.topicLayer=null;Map.backgroundLayer=null;Map.backgroundTopic=null;Map.backgroundLayers={};Map.selectionLayer=null;Map.redliningLayer=null;Map.highlightLayer=null;Map.overlayLayers={}};
Map.setTopicLayer=function(){var a=$.extend({},Config.map.wmsParams,{LAYERS:Map.visibleLayers().join(","),OPACITIES:Map.layerOpacities()});Map.backgroundTopic&&(a.TRANSPARENT=!0);var b=null,a={url:Map.topics[Map.topic].wms_url,params:a,serverType:Config.map.wmsServerType,dpi:Config.map.dpi};Map.topicLayer=null;Map.useTiledWMS?(b=new ol.source.TileWMS(a),b.on("tileloaderror",function(a){alert("Error loading image from QGIS!")}),Map.topicLayer=new ol.layer.Tile({source:b})):(a.ratio=1,b=new ol.source.ImageWMS(a),
b.on("imageloaderror",function(a){alert("Error loading image from QGIS!")}),Map.topicLayer=new ol.layer.Image({source:b}));Map.topicLayer.name="topic";Map.map.addLayer(Map.topicLayer)};
Map.setBackgroundLayer=function(a,b,d){a=d?Config.data.baselayers[b]:Config.data.extralayers[b];var c={};d=0==b&&d&&Eqwc.settings.visibleFirstBaseLayer?!0:!1;switch(a.type){case "OSM":c=new ol.layer.Tile({visible:d,source:new ol.source.OSM});break;case "XYZ":c=$.parseJSON(a.definition);c=new ol.layer.Tile({visible:d,source:new ol.source.XYZ({url:c.url})});break;case "Bing":c=$.parseJSON(a.definition);c=new ol.layer.Tile({visible:d,preload:Infinity,source:new ol.source.BingMaps({key:c.key,imagerySet:c.imagerySet})});
break;case "WMTS":for(var c=$.parseJSON(a.definition),e=[],f=[],g=eval(c.serverResolutions),h=Config.map.projection.getExtent(),l=ol.extent.getWidth(h)/256,m=void 0!==g?g.length:eval(c.numZoomLevels),h=Config.extractStringFromObject("OpenLayers",c.maxExtent),n=0;n<m;++n)e[n]=n,f[n]=l/Math.pow(2,n);void 0!==c.matrixIds&&(e=eval(c.matrixIds));void 0!==g&&(f=g);g=d;d||void 0==c.visibility||(g=c.visibility);c=new ol.layer.Tile({visible:g,extent:projectData.restrictToStartExtent?projectData.extent.split(","):
void 0,source:new ol.source.WMTS({url:c.url,layer:c.layer,matrixSet:c.matrixSet,requestEncoding:c.requestEncoding,style:c.style,projection:Config.map.projection,format:c.format,tileGrid:new ol.tilegrid.WMTS({extent:eval(h),resolutions:f,matrixIds:e})})});break;case "WMS":c=$.parseJSON(a.definition),g=d,d||void 0==c.visibility||(g=c.visibility),c=new ol.layer.Tile({visible:g,source:new ol.source.TileWMS({url:c.url,params:c.params})})}c.name=a.name;Map.map.getLayers().insertAt(b,c);Map.backgroundLayers[c.name]=
c};Map.clearOverlayLayers=function(){for(var a in Map.overlayLayers)Map.map.removeLayer(a);Map.overlayLayers={}};
Map.addOverlayLayer=function(a,b){var d=$.extend({},Config.map.wmsParams,{LAYERS:b.join(","),TRANSPARENT:!0}),d={url:Map.topics[a].wms_url,params:d,extent:Config.map.extent,serverType:Config.map.wmsServerType,dpi:Config.map.dpi},c=null,c=Config.map.useTiledOverlayWMS?new ol.layer.Tile({source:new ol.source.TileWMS(d)}):new ol.layer.Image({source:new ol.source.ImageWMS(d)});c.name="overlay_"+a;void 0!=Map.overlayLayers[a]&&Map.map.removeLayer(Map.overlayLayers[a]);Map.overlayLayers[a]=c;Map.map.addLayer(c)};
Map.toggleOverlayLayer=function(a,b){void 0!=Map.overlayLayers[a]&&Map.overlayLayers[a].setVisible(b)};Map.setSelectionLayer=function(a){null!=Map.selectionLayer&&(Map.map.removeLayer(Map.selectionLayer),Map.selectionLayer=null);null!=a&&(Map.selectionLayer=a,Map.map.addLayer(Map.selectionLayer))};Map.toggleSelectionLayer=function(a){null!=Map.selectionLayer&&Map.selectionLayer.setVisible(a)};
Map.setRedliningLayer=function(a){null!=Map.redliningLayer&&(Map.map.removeLayer(Map.redliningLayer),Map.redliningLayer=null);null!=a&&(Map.redliningLayer=a,Map.map.addLayer(Map.redliningLayer))};Map.toggleRedliningLayer=function(a){null!=Map.redliningLayer&&Map.redliningLayer.setVisible(a)};Map.setHighlightLayer=function(a){null!=Map.highlightLayer&&(Map.map.removeLayer(Map.highlightLayer),Map.highlightLayer=null);null!=a&&(Map.highlightLayer=a,Map.map.addLayer(Map.highlightLayer))};
Map.setLayerVisible=function(a,b,d){Map.layers[a].visible=b;d&&Map.mergeWmsParams({LAYERS:Map.visibleLayers().join(",")})};Map.visibleLayers=function(){var a=[],b;for(b in Map.layers)Map.layers[b].visible&&(projectData.use_ids?a.push(Map.layers[b].id):a.push(Map.layers[b].title));return a};
Map.featureInfoLayers=function(){var a=[],b=Map.map.getView().getResolution(),d;for(d in Map.layers){var c=Map.layers[d];if(c.visible){var e=!0;void 0!=c.minscale&&(e=b>=Map.scaleDenomToResolution(c.minscale,!1));e&&void 0!=c.maxscale&&(e=b<=Map.scaleDenomToResolution(c.maxscale,!1));e&&a.push(d)}}if(b=Eqwc.settings.replaceIdentifyLayerWithView)for(d=0;d<b.length;d++){if(e=c=Eqwc.common.getLayerId(b[d]))e=Eqwc.common.getIdentifyLayerName(c),e=Eqwc.common.getLayerId(e);c=a.indexOf(c);-1<c&&(a[c]=e)}return a};
Map.getGetFeatureInfoUrl=function(a,b){var d=Map.map.getView();return Map.topicLayer.getSource().getGetFeatureInfoUrl(a,d.getResolution(),d.getProjection(),b)};Map.setLayerTransparency=function(a,b,d){Map.layers[a].transparency=b;d&&Map.mergeWmsParams({OPACITIES:Map.layerOpacities()})};Map.layerOpacities=function(){var a=[],b=!1,d;for(d in Map.layers)if(Map.layers[d].visible){var c=Math.round((100-Map.layers[d].transparency)/100*255);a.push(c);b=b||255!=c}return b?a.join(","):null};
Map.refresh=function(){var a=Map.visibleLayers();0<a.length&&Map.mergeWmsParams({LAYERS:a.join(","),OPACITIES:Map.layerOpacities()});Map.topicLayer.setVisible(0<a.length)};Map.redraw=function(){Map.mergeWmsParams({t:(new Date).getTime()})};Map.mergeWmsParams=function(a){var b=Map.topicLayer.getSource();a=$.extend({},b.getParams(),a);b.updateParams(a)};Map.setRotation=function(a){Map.map.getView().setRotation(a)};
Map.scaleDenomToResolution=function(a,b){var d=a/(Map.map.getView().getProjection().getMetersPerUnit()*(Config.map.dpi/0.0254));return b?Map.map.getView().constrainResolution(d):d};Map.setMinScaleDenom=function(a){Map.minResolution=Map.scaleDenomToResolution(a,!0);Map.clampToScale(a)};Map.clampToScale=function(a){a=Map.scaleDenomToResolution(a,!0);Map.map.getView().getResolution()<a&&Map.map.getView().setResolution(a)};
Map.zoomToExtent=function(a,b){Map.map.getView().fit(a,Map.map.getSize());null!=b&&Map.clampToScale(b)};Map.setCenter=function(a){Map.map.getView().setCenter(a)};Map.setScale=function(a){a=Map.scaleDenomToResolution(a,!0);Map.map.getView().setResolution(a)};Map.setZoom=function(a){Map.map.getView().setZoom(a)};Map.updateAndroidLocation=function(a){Map.geolocation.setLocation(a,Gui.tracking)};
Map.toggleTracking=function(a){if(null==Map.geolocation){"undefined"==typeof Android?(Map.geolocation=new ol.Geolocation({projection:Map.map.getView().getProjection(),trackingOptions:{enableHighAccuracy:!0,maximumAge:2E4,timeout:21E3}}),Map.geolocation.set("source","Geolocation API")):(Map.geolocation=new ol.AndroidLocation({projection:Map.map.getView().getProjection()}),Map.geolocation.set("source","Android API"));var b=parseFloat(0<$("#antennaHeight").length?$("#antennaHeight")[0].value:0);isNaN(b)&&
(b=0);var d=0,c="";"function"==typeof Editor&&(d=mobEditor.getAntennaOffset(),b+=d,c=mobEditor.getAntennaType());Map.geolocation.setProperties({altCorrection:0,altCorrectionSource:"",antenna:b,antennaOffset:d,antennaType:c});Map.geolocation.on("error",function(a){alert(a.message);$("#btnLocation .ui-icon").toggleClass("ui-icon-location_on",!1);$("#btnLocation .ui-icon").toggleClass("ui-icon-location_off",!0);Gui.tracking=!1;Gui.showLocationPanel(!1);$("#locationMarker").toggle(!1);Map.geolocationLayer.setVisible(!1)});
Map.geolocation.on("change",function(){var a=Map.geolocation.getPosition();f.setPosition(a);Gui.showLocationPanel(!0);"function"==typeof Editor&&(mobEditor.showEditPanel(!0),mobGoto&&mobGoto.feature&&mobGoto.updateGotoContent());$("#btnInfo").show();Map.geolocationLayer.setVisible(!0)});var e=new ol.Feature;e.setStyle(new ol.style.Style({fill:new ol.style.Fill({color:"rgba(255, 0, 0, 0.05)"})}));var f=new ol.Overlay({element:$('<div id="locationMarker" class="locationMarkerNormal"></div>')[0],positioning:"center-center",
stopEvent:!1});Map.geolocation.on("change:accuracy",function(){var a=Map.geolocation.getAccuracy(),b=$("#locationMarker");"function"==typeof Editor&&(a<EditorConfig.accuracyLimit?(b.addClass("locationMarkerGood").removeClass("locationMarkerNormal"),e.setStyle(new ol.style.Style({fill:new ol.style.Fill({color:"rgba(0, 255, 0, 0.05)"})}))):(b.addClass("locationMarkerNormal").removeClass("locationMarkerGood"),e.setStyle(new ol.style.Style({fill:new ol.style.Fill({color:"rgba(255, 0, 0, 0.05)"})}))))});
Map.geolocation.on("change:accuracyGeometry",function(){e.setGeometry(Map.geolocation.getAccuracyGeometry())});Map.geolocationLayer=new ol.layer.Vector({source:new ol.source.Vector({features:[e]})});Map.geolocationLayer.name="geolocation";Map.map.addLayer(Map.geolocationLayer);Map.map.addOverlay(f)}Map.geolocation.setTracking(a);$("#locationMarker").toggle(a);if(a)Map.geolocation.once("change:position",Map.initialCenterOnLocation);else Gui.showLocationPanel(!1),"function"==typeof Editor&&mobEditor.showEditPanel(!1),
$("#btnInfo").hide(),Map.geolocationLayer.setVisible(!1)};Map.toggleFollowing=function(a){if(null!=Map.geolocation)if(a)Map.geolocation.on("change:position",Map.centerOnLocation);else Map.geolocation.un("change:position",Map.centerOnLocation)};
Map.initialCenterOnLocation=function(){Map.centerOnLocation();if(null!=Config.map.initialGeolocationMaxScale){var a=Map.scaleDenomToResolution(Config.map.initialGeolocationMaxScale,!0);Map.map.getView().getResolution()>a&&Map.map.getView().setResolution(a)}"function"==typeof Editor&&EditorConfig.altCorrectionLayer&&mobEditor.getHeightCorrection()};Map.centerOnLocation=function(){Map.map.getView().setCenter(Map.geolocation.getPosition());Map.clampToScale(Config.map.minScaleDenom.geolocation)};
Map.setWindowOrientation=function(a){Map.windowOrientation=a;null!=Map.deviceOrientation&&Map.deviceOrientation.getTracking()&&void 0!=Map.deviceOrientation.getHeading()&&Map.setRotation(Map.adjustedHeading(-Map.deviceOrientation.getHeading()))};Map.adjustedHeading=function(a){void 0!=Map.windowOrientation&&(a-=Map.windowOrientation*Math.PI/180);return a};
Map.toggleOrientation=function(a){null==Map.deviceOrientation&&(Map.deviceOrientation=new ol.DeviceOrientation,Map.deviceOrientation.on("change:heading",function(a){a=Map.adjustedHeading(-a.target.getHeading());0.0175<Math.abs(Map.map.getView().getRotation()-a)&&Map.setRotation(a)}));Map.deviceOrientation.setTracking(a)};
Map.toggleClickMarker=function(a){null==Map.clickMarker&&(Map.clickMarker=new ol.Overlay({element:$('<div id="clickMarker"></div>')[0],positioning:"center-center",stopEvent:!1}),Map.map.addOverlay(Map.clickMarker));Map.clickMarker.setPosition(a?Map.lastClickPos:void 0)};
Map.toggleScalebar=function(a){if(null==Map.scaleLine){var b=Eqwc.settings.measurementsUnitSystem?Eqwc.settings.measurementsUnitSystem:"metric";"english"==b.toLowerCase()?b="us":"geographic"==b.toLowerCase()&&(b="degrees");Map.scaleLine=new ol.control.ScaleLine({units:b})}a&&null==Map.scaleLine.getMap()?Map.map.addControl(Map.scaleLine):Map.map.removeControl(Map.scaleLine)};Map.toggleClickHandling=function(a){Map.ignoreClick=!a};Map.registerClickHandler=function(a,b){Map.singleClickHandlers[a]=b};
Map.unregisterClickHandler=function(a){Map.singleClickHandlers[a]&&(Map.singleClickHandlers[a].toggle(!1),delete Map.singleClickHandlers[a])};Map.activateClickHandler=function(a){for(var b in Map.singleClickHandlers)Map.singleClickHandlers[b].toggle(!1);null!=a&&Map.singleClickHandlers[a]&&Map.singleClickHandlers[a].toggle(!0)};
Map.featureInfoOnLocation=function(){if(!Map.ignoreClick){var a=Map.geolocation.getPosition();(new FeatureInfo(Gui.showFeatureInfoResults)).callOnLocation(a,Config.featureInfo.useWMSGetFeatureInfo,null);Map.lastClickPos=a}};function MapClickHandler(){this.active=!1}MapClickHandler.prototype={toggle:function(a){this.active=a},isActive:function(){return this.active},handleEvent:function(a){}};function FeatureInfo(a){this.resultsCallback=a}FeatureInfo.prototype=new MapClickHandler;
FeatureInfo.prototype.callOnLocation=function(a,b,d){var c=null;d=null===d?Map.featureInfoLayers():d;Map.toggleClickHandling(!1);b?(b={INFO_FORMAT:Config.featureInfo.format,FEATURE_COUNT:Config.featureInfo.wmsMaxFeatures},"qgis"===Config.map.wmsServerType&&$.extend(b,{FI_POINT_TOLERANCE:Config.featureInfo.tolerances.point,FI_LINE_TOLERANCE:Config.featureInfo.tolerances.line,FI_POLYGON_TOLERANCE:Config.featureInfo.tolerances.polygon,QUERY_LAYERS:d.join(",")}),c=Map.getGetFeatureInfoUrl(a,b)):(b=Map.map.getView(),
c=hiddenProject.getSource().getGetFeatureInfoUrl(a,b.getResolution(),b.getProjection(),{INFO_FORMAT:Config.featureInfo.format,QUERY_LAYERS:d}));$.ajax({url:c,dataType:"text",timeout:5E3,context:this}).done(function(a,b,c){c=null;c="text/xml"===Config.featureInfo.format?this.parseResults([a]):[a];this.resultsCallback(b,c);Map.toggleClickHandling(!0)}).fail(function(a,b,c){this.resultsCallback(b,c);Map.toggleClickHandling(!0)})};
FeatureInfo.prototype.handleEvent=function(a){var b=null,b=Map.featureInfoLayers();Map.toggleClickHandling(!1);if(Config.featureInfo.useWMSGetFeatureInfo){var d={INFO_FORMAT:Config.featureInfo.format,FEATURE_COUNT:Config.featureInfo.wmsMaxFeatures};"qgis"===Config.map.wmsServerType&&$.extend(d,{FI_POINT_TOLERANCE:Math.round(Config.featureInfo.tolerances.point*a.frameState.pixelRatio),FI_LINE_TOLERANCE:Math.round(Config.featureInfo.tolerances.line*a.frameState.pixelRatio),FI_POLYGON_TOLERANCE:Math.round(Config.featureInfo.tolerances.polygon*
a.frameState.pixelRatio),QUERY_LAYERS:b.join(","),WITH_MAPTIP:!0});b=Map.getGetFeatureInfoUrl(a.coordinate,d)}else b=Config.featureInfo.url(Map.topic,a.coordinate,b);$.ajax({url:b,dataType:"text",context:this}).done(function(a,b){var d=null,d="text/xml"===Config.featureInfo.format?this.parseResults([a]):[a];this.resultsCallback(b,d);Map.toggleClickHandling(!0)})};
FeatureInfo.prototype.parseResults=function(a){for(var b=[],d=0;d<a.length;d++){var c=$.parseXML(a[d]);$(c).find("Layer").each(function(){var a=[],c=$(this).attr("name");if(0<$(this).find("Feature").length)$(this).find("Feature").each(function(){var b=[];$(this).find("Attribute").each(function(){"geometry"!=$(this).attr("name")&&b.push({name:$(this).attr("name"),value:$(this).attr("value").replace(/null/ig,Eqwc.settings.noDataValue)})});a.push({id:$(this).attr("id"),attributes:b})});else if(0<$(this).find("Attribute").length){var d=
[];$(this).find("Attribute").each(function(){d.push({name:Eqwc.common.getRasterFieldName(Config.getLayerName(c),$(this).attr("name")),value:$(this).attr("value").replace(/null/ig,Eqwc.settings.noDataValue)})});a.push({id:null,attributes:d})}0<a.length&&b.push({layer:c,features:a})})}return b.reverse()};var Topics={loadTopics:function(a,b){var d=[{name:projectData.project,title:projectData.title,icon:projectData.client_logo,categorytitle:projectData.client_display_name,categorysort:0,categories_topics_sort:0,wms_url:"/proxy/"+projectData.project,background_layer:!1,minscale:Eqwc.settings.mobileMinScale?Eqwc.settings.mobileMinScale:100}];categories={};for(var c=0;c<d.length;c++){var e=d[c];void 0===categories[e.categorytitle]&&(categories[e.categorytitle]=[]);categories[e.categorytitle].push(e)}var d=
[],f;for(f in categories)categories.hasOwnProperty(f)&&(c=categories[f].sort(function(a,b){var c=a.categories_topics_sort-b.categories_topics_sort;if(0===c)c=a.title.localeCompare(b.title);else if(null===a.categories_topics_sort||null===b.categories_topics_sort)c=-c;return c}),d.push({title:f,topics:c}));b(d)}};var Layers={markerPrefix:"____",loadLayers:function(a,b){var d=projectData.layers;groups={};for(var c in d){var e=d[c];e.wfs&&(Config.data.wfslayers[c]=e.layername);e["goto"]&&(Config.data.gotolayers[c]=e.layername);null===e.groupname&&(e.groupname=Layers.markerPrefix+e.layername);void 0===groups[e.groupname]&&(groups[e.groupname]=[]);groups[e.groupname].push(e)}var d=[],f;for(f in groups)groups.hasOwnProperty(f)&&d.push({title:f,layers:groups[f]});f=[];c=RegExp(Layers.markerPrefix);for(e=0;e<d.length;e++){var g=
d[e],h=null;g.title.match(c)?h=f:(h={name:g.title,layers:[]},f.push(h),h=h.layers);for(var l=0;l<g.layers.length;l++)h.push({name:g.layers[l].layername,layers:[]})}b({groups:d,layertree:f})}};var Gui={signedIn:!1,tracking:!1,following:!0,orientation:!0,initialLoad:!0,selectedLayer:null,draggedLayerIndex:null,layerOrderChanged:!1,updateLayout:function(){$("#map").height(window.innerHeight);$("#map").width(window.innerWidth);$("#panelTopics").height(window.innerHeight-60);$("#panelLayerAll").height(window.innerHeight-60);$("#panelLayerOrder").height(window.innerHeight-60);$("#panelFeatureInfo #featureInfoResults").height(window.innerHeight-40);$("#panelSearch .ui-listview").height(window.innerHeight);
$("#panelPropertiesMap").height(window.innerHeight-60);$("#panelPropertiesEditor").height(window.innerHeight-60)},panelSelect:function(a){$("#panelTopics").toggle("panelTopics"===a);$("#panelLayerAll").toggle("panelLayerAll"===a);$("#panelLayerOrder").toggle("panelLayerOrder"===a);$("#buttonTopics").toggleClass("selected","panelTopics"===a);$("#buttonLayerAll").toggleClass("selected","panelLayerAll"===a);$("#buttonLayerOrder").toggleClass("selected","panelLayerOrder"===a)},propertiesSelect:function(a){$("#panelPropertiesMap").toggle("panelPropertiesMap"===
a);$("#panelPropertiesEditor").toggle("panelPropertiesEditor"===a);$("#buttonPropertiesMap").toggleClass("selected","panelPropertiesMap"===a);$("#buttonPropertiesEditor").toggleClass("selected","panelPropertiesEditor"===a)},showLocationPanel:function(a){if(a){a=2;"degrees"==proj4.defs[Map.userCrs].units&&(a=4);var b=Map.geolocation.getPosition(),d=new ol.geom.Point(b);Map.userCrs!=projectData.crs&&d.transform(projectData.crs,Map.userCrs);var b=Map.geolocation.getAccuracy(),c=Map.geolocation.getAltitude();
"function"==typeof Map.geolocation.getAltitudeCorrected&&(c=Map.geolocation.getAltitudeCorrected());var e=Map.geolocation.getProperties(),f=Map.geolocation.getHeading(),g=Map.geolocation.getSpeed();a=[d.getCoordinates()[0].toFixed(a)+", "+d.getCoordinates()[1].toFixed(a)];Eqwc.settings.mobileShowAccuracy&&("function"==typeof Editor?b<EditorConfig.accuracyLimit?a.push(I18n.geolocation.accuracy+": "+b.toPrecision(3)+" m"):a.push('<span style="color:red;font-weight:bold;">'+I18n.geolocation.accuracy+
": "+b.toPrecision(4)+" m </span>"):a.push(I18n.geolocation.accuracy+": "+b.toPrecision(3)+" m"));c&&(a.push(I18n.geolocation.altitude+": "+c.toFixed(2)+" m"),0<e.altCorrection&&a.push(e.altCorrectionSource),a.push("AH: "+parseFloat(e.antenna-e.antennaOffset)+" m "+e.antennaType));f&&1<g&&(a.push(I18n.geolocation.heading+": "+Math.round(360*f/(2*Math.PI))+"&deg;"),a.push(I18n.geolocation.speed+": "+(3.6*g).toFixed(1)+" km/h"));$("#locationPanel").html(a.join("<br />"));$("#locationPanel").show()}else $("#locationPanel").hide(),
"function"==typeof Editor&&mobGoto&&mobGoto.showGotoPanel(!1)},loadTopics:function(a){var b="",d="";Map.topics={};for(var c=0;c<a.length;c++){for(var e=a[c],f=0;f<e.topics.length;f++){var g=e.topics[f];!1!=g.main_layer&&(b+='<a href="'+Eqwc.settings.gisPortalRoot+'" target="_self"><img style="padding:5px" src="'+g.icon+'"/></a>');Map.topics[g.name]={title:g.title,wms_url:g.wms_url,background_layer:g.background_layer,overlay_layer:g.overlay_layer,minscale:g.minscale,bg_topic:g.bg_topic,overlay_topics:g.overlay_topics}}d+=
'<div id="topicList" data-role="collapsible">';d+="<h4>"+g.title+"</h4>";d+="<p>"+projectData.project+"</p>";d+="<p>"+projectData.crs+"</p>";"{}"!=projectData.description&&(d+="<p>"+projectData.description+"</p>");d+="</div>"}a=$("#topicMain");a.prepend(d);a.prepend(b);a.find("div[data-role=collapsible]").collapsible({theme:"c",refresh:!0});Gui.selectTopic(Config.permalink.initialTopic||Config.data.initialTopic)},selectTopic:function(a){Map.clearLayers();Map.topic=a;Map.setMinScaleDenom(Map.topics[Map.topic].minscale||
Config.map.minScaleDenom.map);Map.backgroundTopic=Map.topics[Map.topic].bg_topic||null;Gui.initialLoad&&Config.permalink.initialBackgroundTopic&&(Map.backgroundTopic=Config.permalink.initialBackgroundTopic);void 0!=Map.topics[Map.backgroundTopic]&&Map.topics[Map.backgroundTopic].background_layer||(Map.backgroundTopic=null);Layers.loadLayers(null,Gui.loadLayers);Gui.loadExtraLayers();Gui.loadBackgroundLayers()},loadLayers:function(a){function b(d,f,g,h){if(0<d.layers.length)c+='<div data-role="collapsible" data-theme="c"',
Config.gui.useLayertreeGroupCheckboxes&&(c+=' data-groupcheckbox="true"'),c+=">",c+="<h3>"+d.name+"</h3>";else{var p=f||Layers.markerPrefix+d.name,k=$.grep(a.groups,function(a){return a.title===p})[0];if(void 0!=k){k=$.grep(k.layers,function(a){return a.layername===d.name})[0];if(-1<Eqwc.common.getHiddenLayersFromSettings().indexOf(k.layername)||Config.baseLayerExists(k.layername)||Config.extraLayerExists(k.layername))return;c+="<label>";c+='<input type="'+h+'" ';null!=f&&(c+='data-role="none" ');
c+='name="'+k.layername+'" ';c+='data-layer="'+k.id+'" ';k.visini&&(c+="checked ");c+=">"+k.toclayertitle;c+="</label>";e.push({id:k.id,layername:k.layername,title:k.toclayertitle,wms_sort:k.wms_sort,visible:k.visini,minscale:k.minscale,maxscale:k.maxscale,hidden_attributes:k.hidden_attributes,hidden_values:k.hidden_values})}}for(f=0;f<d.layers.length;f++)b(d.layers[f],d.name,g+1,"checkbox");0<d.layers.length&&(c+="</div>")}function d(){var a=$(this).children(".ui-collapsible-content").children("label");
a.find(':checkbox[data-role="none"]').attr("data-role",null);a.trigger("create");$(this).unbind("expand",d)}for(var c="",e=[],f=0;f<a.layertree.length;f++)b(a.layertree[f],null,0,"checkbox");$("#panelLayerAll").html(c);$("#panelLayerAll").trigger("create");$("#panelLayerAll").find(".ui-collapsible").bind("expand",d);$("#panelLayerAll").children(".ui-collapsible[data-groupcheckbox=true]").bind("groupchange",function(a){var b=Map.visibleLayers();$(this).find(":checkbox").each(function(a){-1!=b.indexOf($(this).data("layer"))!=
$(this).is(":checked")&&(Map.setLayerVisible($(this).data("layer"),$(this).is(":checked"),!1),Gui.updateLayerOrder($(this).data("layer"),$(this).is(":checked")))})});e=e.sort(function(a,b){return a.wms_sort-b.wms_sort});Map.layers={};for(f=0;f<e.length;f++){var g=e[f];Map.layers[g.id]={id:g.id,title:g.title,visible:g.visible,wms_sort:g.wms_sort,minscale:g.minscale,maxscale:g.maxscale,hidden_attributes:g.hidden_attributes,hidden_values:g.hidden_values,transparency:0}}Gui.layerOrderChanged=!1;Gui.initialLoad&&
Gui.applyPermalink();Map.setTopicLayer();Gui.resetLayerOrder();g=Map.topics[Map.topic].overlay_topics||[];if(Gui.initialLoad&&null!=Config.permalink.initialOverlayTopics)for(f=0;f<Config.permalink.initialOverlayTopics.length;f++){var h=Config.permalink.initialOverlayTopics[f];-1==g.indexOf(h)&&g.push(h)}Gui.setupOverlayTopics(g);Config.permalink.addOverlays(Gui.setSelectionLayer,Gui.setRedliningLayer);Gui.initialLoad&&(Gui.initialLoad=!1);$.event.trigger({type:"topiclayersloaded",topic:Map.topic})},
loadBackgroundLayers:function(a){if(0!=Config.data.baselayers.length){a='<div data-role="collapsible" data-theme="c">'+("<h3>"+I18n.layers.background+"</h3>");for(var b=0;b<Config.data.baselayers.length;b++){var d=Config.data.baselayers[b],c="";0==b&&Eqwc.settings.visibleFirstBaseLayer&&(c=' checked="checked"');a+='<label><input type="checkbox" name="_background_" id="'+d.name+'" data-background="true"'+c+">"+d.title+"</label>";Map.setBackgroundLayer(d.name,b,!0)}a+="</div>";$("#panelLayerAll").append(a);
$("#panelLayerAll").trigger("create");$("#panelLayerAll :checkbox[data-background=true]").on("change",function(a){a=$(this).attr("id");var b=Map.backgroundLayers[a],c=$(this).is(":checked");b.setVisible(c);$("#panelLayerAll :checkbox[data-background=true]").not($(this)).prop("checked",!1).checkboxradio("refresh");for(b=0;b<Config.data.baselayers.length;b++)c=Config.data.baselayers[b].name,c!==a&&Map.backgroundLayers[c].setVisible(!1)})}},loadExtraLayers:function(a){if(void 0!=Config.data.extralayers){a=
'<div data-role="collapsible" data-theme="c">'+("<h3>"+I18n.layers.overlays+"</h3>");for(var b=0;b<Config.data.extralayers.length;b++){var d=Config.data.extralayers[b],c="";$.parseJSON(d.definition).visibility&&(c=' checked="checked"');a+='<label><input type="checkbox" name="_extra_" id="'+d.name+'" data-extra="true"'+c+">"+d.title+"</label>";Map.setBackgroundLayer(d.name,b,!1)}a+="</div>";$("#panelLayerAll").append(a);$("#panelLayerAll").trigger("create");$("#panelLayerAll :checkbox[data-extra=true]").bind("change",
function(a){a=$(this).attr("id");a=Map.backgroundLayers[a];var b=$(this).is(":checked");a.setVisible(b)})}},setupOverlayTopics:function(a){a=$.grep(a,function(a,b){return void 0!=Map.topics[a]&&Map.topics[a].overlay_layer});Map.clearOverlayLayers();$("#overlayTopics").remove();if(0<a.length){var b;b='<div id="overlayTopics" data-role="collapsible" data-theme="c" data-groupcheckbox="false">'+("<h3>"+I18n.layers.overlays+"</h3>");for(var d=a.length-1;0<=d;d--){var c=a[d];b+="<label>";b+='<input type="checkbox" ';
b+='name="overlayTopic_'+c+'" ';b+='data-overlay_topic="'+c+'" ';b+="checked";b+=">"+Map.topics[c].title;b+="</label>"}b+="</div>";$("#panelLayerAll").append(b);$("#panelLayerAll").trigger("create");for(d=0;d<a.length;d++)Gui.addOverlayTopicLayer(a[d]);$("#panelLayerAll :checkbox[data-overlay_topic]").bind("change",function(a){Map.toggleOverlayLayer($(this).data("overlay_topic"),$(this).is(":checked"))})}},addOverlayTopicLayer:function(a){Layers.loadLayers(Config.data.layersUrl(a),function(b){var d=
b.groups;b=[];for(var c=0;c<d.length;c++)for(var e=d[c],f=0;f<e.layers.length;f++){var g=e.layers[f];g.visini&&b.push({layername:g.layername,wms_sort:g.wms_sort})}b=b.sort(function(a,b){return a.wms_sort-b.wms_sort});d=[];for(c=0;c<b.length;c++)d.push(b[c].layername);Map.addOverlayLayer(a,d)})},setSelectionLayer:function(a){if(null!=a){var b='<label><input type="checkbox" name="_selection_" data-selection="true" checked>'+I18n.layers.selection+"</label>";$("#panelLayerAll").append(b);$("#panelLayerAll").trigger("create");
$("#panelLayerAll :checkbox[data-selection=true]").bind("change",function(a){Map.toggleSelectionLayer($(this).is(":checked"))})}else $("#panelLayerAll :checkbox[data-selection=true]").parent(".ui-checkbox:first").remove();Map.setSelectionLayer(a)},setRedliningLayer:function(a){if(null!=a){var b='<label><input type="checkbox" name="_redlining_" data-redlining="true" checked>'+I18n.layers.redlining+"</label>";$("#panelLayerAll").append(b);$("#panelLayerAll").trigger("create");$("#panelLayerAll :checkbox[data-redlining=true]").bind("change",
function(a){Map.toggleRedliningLayer($(this).is(":checked"))})}else $("#panelLayerAll :checkbox[data-redlining=true]").parent(".ui-checkbox:first").remove();Map.setRedliningLayer(a)},resetLayerOrder:function(){var a="",b;for(b in Map.layers)Map.layers[b].visible&&(a='<li data-layer="'+b+'" data-wms_sort="'+Map.layers[b].wms_sort+'">'+Map.layers[b].title+"</li>"+a);$("#listOrder").html(a);$("#listOrder").listview("refresh");Gui.selectLayer(null)},updateLayerOrder:function(a,b){if(b){var d='<li data-layer="'+
a+'" data-wms_sort="'+Map.layers[a].wms_sort+'">'+Map.layers[a].title+"</li>";if(Gui.layerOrderChanged)$("#listOrder").prepend(d);else{var c=$("#listOrder li").filter(function(){return $(this).data("wms_sort")<Map.layers[a].wms_sort}).first();0<c.length?c.before(d):(c=$("#listOrder li").filter(function(){return $(this).data("wms_sort")>Map.layers[a].wms_sort}).last(),0<c.length?c.after(d):$("#listOrder").prepend(d))}}else $('#listOrder li[data-layer="'+a+'"]').remove();$("#listOrder").listview("refresh");
Gui.onLayerOrderChanged(null,null)},onLayerDrag:function(a,b){Gui.draggedLayerIndex=$("#listOrder li").index(b.item)},onLayerOrderChanged:function(a,b){null!=b&&$("#listOrder li").index(b.item)!=Gui.draggedLayerIndex&&(Gui.layerOrderChanged=!0);Gui.selectLayer(null);var d={};$($("#listOrder li").get().reverse()).each(function(a){a=$(this).data("layer");d[a]=Map.layers[a]});for(var c in Map.layers)void 0===d[c]&&(d[c]=Map.layers[c]);Map.layers=d;Map.refresh()},selectLayer:function(a){$("#listOrder li").removeClass("selected");
Gui.selectedLayer=a;null!=Gui.selectedLayer?($('#listOrder li[data-layer="'+a+'"]').addClass("selected"),$("#sliderTransparency").val(Map.layers[a].transparency).slider("refresh"),$("#sliderTransparency").slider("enable")):($("#sliderTransparency").val(0).slider("refresh"),$("#sliderTransparency").slider("disable"))},showFeatureInfoResults:function(a,b){"success"!=a?(Map.toggleClickMarker(!0),alert(b)):("text/xml"===Config.featureInfo.format?Gui.showXMLFeatureInfoResults(b):$("#featureInfoResults").html(b.join("")),
$("#panelFeatureInfo").panel("open"),Map.toggleClickMarker(!0))},showXMLFeatureInfoResults:function(a){var b="",d=Eqwc.settings.qgisFilesFieldAlias?Eqwc.settings.qgisFilesFieldAlias:"files",d=d.toUpperCase();"function"==typeof Editor&&mobEditor.layer&&(b+='<a href="javascript:mobEditor.addPointOnClickPos();" data-theme="a" data-inline="true" data-mini="true" data-role="button">'+TR.editAdd+"</a>");for(var c=0;c<a.length;c++){var e=a[c],f=Map.layers[e.layer];void 0==f&&(f=Config.getLayerName(e.layer),
f=Eqwc.common.getIdentifyLayerNameRevert(f),f=Eqwc.common.getLayerId(f),f=Map.layers[f]);var g=e.layer;void 0!=f&&(g=f.title);b+='<div data-role="collapsible" data-collapsed="false" data-theme="c">';b+="<h3>"+g+" ("+e.features.length+")</h3>";for(g=0;g<e.features.length;g++){var h=e.features[g],l=null===h.id?I18n.featureInfo.raster:I18n.featureInfo.feature+h.id,b=b+'<div class="feature" data-role="collapsible" data-collapsed="false" data-theme="c">',b=b+("<h3>"+l+"</h3>");"function"==typeof Editor&&
Config.data.wfslayers[f.id]&&(b+="<a href=\"javascript:Eqwc.common.callEditor('"+f.id+"',"+h.id+', \'edit\');" data-theme="b" data-inline="true" data-mini="true" data-role="button">'+TR.editEdit+"</a>");"function"==typeof Editor&&Config.data.gotolayers[f.id]&&(b+="<a href=\"javascript:Eqwc.common.callEditor('"+f.id+"',"+h.id+', \'goto\');" data-theme="e" data-inline="true" data-mini="true" data-role="button">'+I18n.editor["goto"]+"</a>");b+='<ul class="ui-listview-inset ui-corner-all" data-role="listview">';
for(l=0;l<h.attributes.length;l++){var m=h.attributes[l],n=m.name.toUpperCase(),b=b+"<li>";if(n==d){if(""<m.value){var q=$.parseJSON(m.value),p=[];if(null===q)m.value=Eqwc.settings.noDataValue;else{for(var k=0;k<q.length;k++)p.push(Eqwc.common.manageFile(q[k],!0));m.value=p.join("</br>")}}}else m.value=Eqwc.common.createHyperlink(m.value,null,null);"MAPTIP"!==n&&n!==d&&(b+='<span class="name">'+m.name+": </span>");b+='<span class="value">'+m.value+"</span>";b+="</li>"}b+="</ul>";b+="</div>"}b+="</div>"}0==
a.length&&(b+="</br>"+I18n.featureInfo.noFeatureFound);$("#featureInfoResults").html(b);$("#featureInfoResults").trigger("create")},showSearchResults:function(a){$("#searchResultsList").empty();for(var b=0;b<a.length;b++){var d=a[b];null!=d.category&&$("#searchResultsList").append($('<li class="category-title">'+d.category+"</li>"));for(var c=0;c<d.results.length;c++){var e=d.results[c],f=$('<li><a href="#">'+e.name+"</a></li>");f.data("bbox",e.bbox);f.data("highlight",e.highlight);f.data("point",
e.point);$("#searchResultsList").append(f)}}$("#searchResultsList").listview("refresh");$("#searchResults").show()},jumpToSearchResult:function(a){Map.searchMarker.setPosition(a.getCoordinates());Map.zoomToExtent(a.getExtent(),Config.map.minScaleDenom.search);$("#switchFollow").val("off");$("#switchFollow").slider("refresh");Gui.toggleFollowing(!1);$("#panelSearch").panel("close")}};
$(document).bind("pageinit",function(){$("#listOrder").sortable();$("#listOrder").bind("sortstart",Gui.onLayerDrag);$("#listOrder").bind("sortstop",Gui.onLayerOrderChanged)});
Gui.updateTranslations=function(){document.title=I18n.title;$("#panelSearch b").html(I18n.search.header);$("#panelSearch #searchResults b").html(I18n.search.results);$("#panelProperties #buttonPropertiesMap .ui-btn-text").html(I18n.properties.header);$("#panelProperties label[for=switchFollow]").html(I18n.properties.mapFollowing);$("#panelProperties label[for=switchOrientation]").html(I18n.properties.mapRotation);$("#panelProperties label[for=switchScale]").html(I18n.properties.scaleBar);$("#panelProperties .ui-slider-label:contains(Ein)").html(I18n.properties.on);
$("#panelProperties .ui-slider-label:contains(Aus)").html(I18n.properties.off);$("#panelProperties #buttonLogo .ui-btn-text").html(I18n.properties.about);$("#dlgAbout h1").html(I18n.about.header);$("#panelProperties #buttonShare .ui-btn-text").html(I18n.properties.share);$("#panelProperties #buttonLogin .ui-btn-text").html(I18n.properties.login);$("#panelProperties #buttonLoginSSL .ui-btn-text").html(I18n.properties.login);$("#dlgLogin h1").html(I18n.login.header);$("#dlgLogin label[for=user]").html(I18n.login.user);
$("#dlgLogin label[for=password]").html(I18n.login.password);$("#dlgLogin #buttonSignIn .ui-btn-text").html(I18n.login.signIn);$("#dlgLogin #buttonLoginCancel .ui-btn-text").html(I18n.login.cancel);$("#panelProperties #buttonSignOut .ui-btn-text").html(I18n.login.signOut);$("#panelLayer #buttonTopics .ui-btn-text").html(I18n.layers.project);$("#panelLayer #buttonLayerAll .ui-btn-text").html(I18n.layers.layers);$("#panelLayer #buttonLayerOrder .ui-btn-text").html(I18n.layers.layerOrder);$("#panelLayer #sliderTransparency-label").html(I18n.layers.transparency);
$("#panelFeatureInfo b").html(I18n.featureInfo.header)};Gui.toggleFollowing=function(a){Gui.following=a;Map.toggleFollowing(Gui.tracking&&Gui.following)};Gui.toggleOrientation=function(a){Gui.orientation=a;Map.toggleOrientation(Gui.orientation)};
Gui.applyPermalink=function(){null!=Config.permalink.startExtent?Map.zoomToExtent(Config.permalink.startExtent,null):(null!=Config.permalink.startCenter&&Map.setCenter(Config.permalink.startCenter),null!=Config.permalink.startScale?Map.setScale(Config.permalink.startScale):null!=Config.permalink.startZoom&&Map.setZoom(Config.permalink.startZoom));var a=function(a,b){Map.layers[a].visible=b;var c=$('#panelLayerAll :checkbox[data-layer="'+a+'"]');c.is(":checked")!=b&&c.prop("checked",b).checkboxradio("refresh").trigger("change")};
if(null!=Config.permalink.activeLayers){var b=[],d=!1,c=-1,e;for(e in Map.layers){var f=$.inArray(e,Config.permalink.activeLayers),g=-1!=f;a(e,g);g&&(b.push({layername:e,sort:f}),d||(d=f<c,c=f))}b=b.sort(function(a,b){return a.sort-b.sort});a={};for(c=0;c<b.length;c++)e=b[c].layername,a[e]=Map.layers[e];for(e in Map.layers)void 0===a[e]&&(a[e]=Map.layers[e]);Map.layers=a;Gui.layerOrderChanged=d}else if(null!=Config.permalink.inactiveLayers)for(e in Map.layers)f=$.inArray(e,Config.permalink.inactiveLayers),
-1!=f&&a(e,!1);if(null!=Config.permalink.opacities)for(e in Config.permalink.opacities)void 0!=Map.layers[e]&&(b=Math.round((255-Config.permalink.opacities[e])/255*100),Map.layers[e].transparency=b);Config.permalink.openLogin&&Config.sslLogin&&UrlParams.useSSL&&!Gui.signedIn&&($("#panelProperties").panel("open"),$("#dlgLogin").popup("open"))};
Gui.loginStatus=function(a){a.success=!0;a.user=projectData.user;a.success&&($("#dlgLogin").popup("close"),Eqwc.settings.useGisPortal?$("#buttonSignOut .ui-btn-text").html(a.user):$("#buttonSignOut .ui-btn-text").html(I18n.login.signOut+" - "+a.user),$("#panelProperties").panel("close"));Gui.toggleLogin(a.success)};
Gui.login=function(a){a.success?(Topics.loadTopics(null,Gui.loadTopics),$("#dlgLogin").popup("close"),Eqwc.settings.useGisPortal?$("#buttonSignOut .ui-btn-text").html(a.user):$("#buttonSignOut .ui-btn-text").html(I18n.login.signOut+" - "+a.user),Gui.toggleLogin(!0),$("#panelProperties").panel("close")):alert(I18n.login.signInFailed)};Gui.logout=function(){$("#panelProperties").panel("close");window.location.href=Eqwc.settings.useGisPortal?Eqwc.settings.gisPortalProfile:"./admin/login.php?action=logout"};
Gui.toggleLogin=function(a){Gui.signedIn=a;$("#buttonLogin").toggle(!a);$("#buttonSignOut").toggle(a)};Gui.fillMapCrs=function(){$.each(Config.map.projectionList,function(a,b){$("#mapCrs").append($("<option>",{value:b[0],text:b[1]}))});$("#mapCrs").on("change",function(){Map.userCrs=this.value;$("#locationPanel").is(":visible")&&Map.geolocation&&Gui.showLocationPanel(!0)});$("#mapCrs").val(projectData.crs).change()};
Gui.initViewer=function(){Gui.updateTranslations();Gui.fillMapCrs();Gui.updateLayout();$(window).on("resize",function(){Gui.updateLayout()});Map.setWindowOrientation(window.orientation);$(window).on("orientationchange",function(a){Map.setWindowOrientation(window.orientation)});Map.createMap();Gui.updateLayout();$("#buttonTopics").on("tap",function(){Gui.panelSelect("panelTopics")});$("#buttonLayerAll").on("tap",function(){Gui.panelSelect("panelLayerAll")});$("#buttonLayerOrder").on("tap",function(){Gui.panelSelect("panelLayerOrder")});
$("#buttonPropertiesMap").on("tap",function(){Gui.propertiesSelect("panelPropertiesMap")});$("#buttonPropertiesEditor").on("tap",function(){Gui.propertiesSelect("panelPropertiesEditor")});$("#switchFollow").val(Config.defaultProperties.following?"on":"off");$("#switchFollow").slider("refresh");Gui.toggleFollowing(Config.defaultProperties.following);$("#switchOrientation").val(Config.defaultProperties.orientation?"on":"off");$("#switchOrientation").slider("refresh");Gui.toggleOrientation(Config.defaultProperties.orientation);
$("#switchScale").val(Config.defaultProperties.scalebar?"on":"off");$("#switchScale").slider("refresh");Map.toggleScalebar(Config.defaultProperties.scalebar);Topics.loadTopics(null,Gui.loadTopics);$("#topicList").delegate("li.topic","vclick",function(a){Gui.selectTopic($(this).data("topic"));$("#panelLayer").panel("close")});$("#panelLayerAll").delegate(":checkbox[data-layer]","change",function(a){a=projectData.use_ids?$(this).data("layer"):projectData.layers[$(this).data("layer")].layername;-1!=
Map.visibleLayers().indexOf(a)!=$(this).is(":checked")&&(Map.setLayerVisible($(this).data("layer"),$(this).is(":checked"),!1),Gui.updateLayerOrder($(this).data("layer"),$(this).is(":checked")))});Gui.panelSelect("panelLayerAll");Gui.propertiesSelect("panelPropertiesMap");$("#listOrder").delegate("li","vclick",function(){Gui.selectLayer($(this).data("layer"))});$("#sliderTransparency").on("slidestop",function(){Map.setLayerTransparency(Gui.selectedLayer,$(this).val(),!0)}).parent().on("swipeleft",
function(a,b){a.stopPropagation()});$(document).on("maprotation",function(a){$("#btnCompass").find(".ui-icon").css("transform","rotate("+a.rotation+"rad)")});$("#btnCompass").on("tap",function(){Map.setRotation(0)});projectData.geolocation||$("#btnLocation").hide();$("#locationPanel").hide();$("#btnInfo").hide();$("#gotoPanel").hide();$("#editPanel").hide();$("#btnLocation").on("tap",function(){Gui.tracking=!Gui.tracking;$("#btnLocation .ui-icon").toggleClass("ui-icon-location_off",!Gui.tracking);
$("#btnLocation .ui-icon").toggleClass("ui-icon-location_on",Gui.tracking);Map.toggleTracking(Gui.tracking);Gui.tracking&&($("#locationPanel").html(I18n.geolocation.obtaining),$("#locationPanel").show());Map.toggleFollowing(Gui.tracking&&Gui.following)});$("#btnInfo").click(Map.featureInfoOnLocation);var a=new FeatureInfo(Gui.showFeatureInfoResults);Map.registerClickHandler("featureInfo",a);Map.activateClickHandler("featureInfo");$("#panelFeatureInfo").on("panelclose",function(){Map.toggleClickMarker(!1)});
$("#featureInfoResults").parent().on("swipeleft",function(a,b){a.stopPropagation()});Config.search||$("#btnSearching").addClass("ui-disabled");var b=function(){$("#searchResults").hide();Map.setHighlightLayer(null);Map.searchMarker.setPosition(void 0)};$("#searchInput").bind("change",function(a){""==$(this).val()&&b()});$("#searchForm").bind("submit",function(a){b();var d=$("#searchInput").val();""!=d&&(Config.search.submit(d,Gui.showSearchResults),$("#searchInput").blur());a.preventDefault();a.stopPropagation()});
$("#searchResultsList").delegate("li","vclick",function(){null!=$(this).data("point")&&Gui.jumpToSearchResult($(this).data("point"));void 0!=$(this).data("highlight")&&Config.search.highlight($(this).data("highlight"),Map.setHighlightLayer)});$("#switchFollow").on("change",function(a){Gui.toggleFollowing("on"==$(this).val())}).parent().on("swiperight",function(a,b){a.stopPropagation()});$("#switchOrientation").on("change",function(a){Gui.toggleOrientation("on"==$(this).val())}).parent().on("swiperight",
function(a,b){a.stopPropagation()});$("#switchScale").on("change",function(a){Map.toggleScalebar("on"==$(this).val())}).parent().on("swiperight",function(a,b){a.stopPropagation()});$("#aboutContent").html(I18n.about.content);$("#buttonShare").toggle(!Config.gui.hideShareButton);$("#buttonLogin").toggle(!Config.gui.hideLoginButton);$("#buttonLoginSSL").hide();$("#buttonSignOut").hide();if(!Config.gui.hideLoginButton)if(Config.sslLogin&&!UrlParams.useSSL){var a=UrlParams.baseUrl.replace(/^http:/,"https:"),
d=$.extend({openLogin:!0},UrlParams.params),a=a+("?"+$.param(d));$("#buttonLoginSSL").attr("href",a);$("#buttonLoginSSL").show();$("#buttonLogin").hide()}else $("#buttonSignIn").on("tap",function(){Config.login.signIn($("#user").val(),$("#password").val(),Gui.login)}),$("#buttonLoginCancel").on("tap",function(){$("#dlgLogin").popup("close")}),$("#buttonSignOut").on("tap",function(){Config.login.signOut(Gui.logout)}),Config.login.status(Gui.loginStatus);$("#panelFeatureInfo, #panelLayer, #panelSearch").on("panelopen",
function(){Map.toggleClickHandling(!1)});$("#panelFeatureInfo, #panelLayer, #panelSearch").on("panelclose",function(){Map.toggleClickHandling(!0)});Map.searchMarker=new ol.Overlay({element:$('<div id="searchMarker"></div>')[0],positioning:"center-center",stopEvent:!1});Map.map.addOverlay(Map.searchMarker);Config.customInitViewer()};$(document).ready(function(a){UrlParams.parse();Config.permalink.read(UrlParams.params,Gui.initViewer)});
