/*
 *
 * eqwc_mobile.js -- build of Extended QGIS Web Client
 *
 * version: 1.11.11
 * buildDate: Wed Oct  2 10:40:26 CEST 2024
 *
 * Copyright (2014-2021), Level2, All rights reserved.
 * More information at https://level2.si
 *
 */
Array.prototype.forEach||(Array.prototype.forEach=function(a,b){var c,d;if(null==this)throw new TypeError("this is null or not defined");var e=Object(this),f=e.length>>>0;if("[object Function]"!=={}.toString.call(a))throw new TypeError(a+" is not a function");b&&(c=b);for(d=0;d<f;){var g;Object.prototype.hasOwnProperty.call(e,d)&&(g=e[d],a.call(c,g,d,e));d++}});null===projectData.search&&Eqwc.settings.search&&(projectData.search=Eqwc.settings.search);null===projectData.geoCode&&null===projectData.wsgi&&Eqwc.settings.geoCode&&(projectData.geoCode=Eqwc.settings.geoCode);null===projectData.wsgi&&null===projectData.geoCode&&Eqwc.settings.wsgi&&(projectData.wsgi=Eqwc.settings.wsgi);null===projectData.locationServices&&Eqwc.settings.locationServices&&(projectData.locationServices=Eqwc.settings.locationServices);
null===projectData.defaultCoordinatesCrsCode&&Eqwc.settings.defaultCoordinatesCrsCode&&(projectData.defaultCoordinatesCrsCode=Eqwc.settings.defaultCoordinatesCrsCode);null===projectData.expandAllGroups&&Eqwc.settings.expandAllGroups&&(projectData.expandAllGroups=Eqwc.settings.expandAllGroups);Eqwc.geolocationErrors={PERMISSION_DENIED:1,POSITION_UNAVAILABLE:2,TIMEOUT:3};Eqwc.tooltips={};Eqwc.common={};
Eqwc.common.createHyperlink=function(a,b,c){if(null==a||""==a||"number"==typeof a)return a;null==b&&(b=a);try{/^((http|https|ftp):\/\/)./i.test(a)?/\<a./i.test(a)||(a='<a class="link" href="'+a+'" target="_blank">'+b+"</a>"):-1<b.indexOf("href=")&&-1==b.indexOf(" target=")?a=b.replaceAll("<a ",'<a target="_blank"'):10<b.length&&"undefined"!=typeof Ext&&(a="<div style='overflow: hidden; text-overflow: ellipsis; white-space: nowrap;' ext:qtip='"+b+"'>"+b+"</div>"),""<c&&RegExp(c,"i").test(a)&&(a='<a href="/'+
a+'" target="_blank">'+b+"</a>")}catch(d){return b}finally{return a}};Eqwc.common.manageFile=function(a,b){var c=!1;if(b){var d=a.split(".")[1].toLowerCase();if("jpg"==d||"jpeg"==d||"gif"==d||"png"==d)c=!0}d=window.location.origin;d=1==projectData.uploadDir.split(".").length?d+projectData.uploadDir:d+projectData.uploadDir.split(".")[1];return c?"<a target='_blank' href='"+d+a+"'><img src='"+d+"thumb/"+a+"'></a>":Eqwc.common.createHyperlink(d+a,a,null)};
Eqwc.common.getRasterFieldName=function(a,b){return Eqwc.settings.overWriteRasterFieldName&&Eqwc.settings.overWriteRasterFieldName[a]?Eqwc.settings.overWriteRasterFieldName[a][0]==b?Eqwc.settings.overWriteRasterFieldName[a][1]:b:b};Eqwc.common.layerFieldNameExists=function(a,b){for(var c=wmsLoader.layerProperties[a],d=0;d<c.attributes.length;d++)if(c.attributes[d].name==b)return!0;return!1};Eqwc.common.lookup=function(a,b,c){for(var d=0,e=a.length;d<e;d++)if(a[d]&&a[d][b]===c)return a[d]};
Eqwc.common.getIdentifyLayerName=function(a){var b=projectData.layers[a];if("undefined"==typeof b)return a;if(b.identifyname)return b.identifyname;b=b.layername;Eqwc.settings.replaceIdentifyLayerWithView&&-1<Eqwc.settings.replaceIdentifyLayerWithView.indexOf(b)&&Eqwc.common.getLayerId(b+"_view")&&(b+="_view");return projectData.layers[a].identifyname=b};
Eqwc.common.getIdentifyLayerNameRevert=function(a){var b;return-1<a.indexOf("_view")&&(b=a.split("_view")[0],Eqwc.settings.replaceIdentifyLayerWithView&&-1<Eqwc.settings.replaceIdentifyLayerWithView.indexOf(b))?b:a};Eqwc.common.getHiddenLayersFromSettings=function(){var a=[Eqwc.settings.QgisUsersPrintName],b=Eqwc.settings.replaceIdentifyLayerWithView;if(b)for(var c=0;c<b.length;c++){var d=Eqwc.common.getLayerId(b[c]);d&&(d=Eqwc.common.getIdentifyLayerName(d),b[c]!=d&&a.push(d))}return a};
Eqwc.common.getProjectUrl=function(){return projectData.gis_projects.path+projectData.project};Eqwc.common.getRootUrl=function(a){return a.toString().replace(/^(.*\/\/[^\/?#]*).*$/,"$1")};Eqwc.common.getLayerId=function(a){for(var b in projectData.layers)if(projectData.layers[b].layername===a)return projectData.layers[b].id;return!1};
Eqwc.common.parseInputTextToCoord=function(a){var b=[],c=[];-1<a.indexOf(",")?c=a.split(","):-1<a.indexOf(";")?c=a.split(";"):-1<a.indexOf(" ")&&(c=a.split(" "));if(0==c.length)return!1;for(var d in c)isNaN(parseFloat(c[d]))||b.push(parseFloat(c[d]));return 0==b.length?!1:b};Eqwc.common.reverseArray=function(a){for(var b=[],c=a.length-1;0<=c;c--)b.push(a[c]);return b};
Eqwc.common.redirect=function(){-1<window.location.href.toLowerCase().indexOf("public=on")?window.location.href=window.location.href:Eqwc.settings.useGisPortal?window.location.href=Eqwc.settings.gisPortalRoot+"login?ru="+Eqwc.common.getProjectUrl():window.location.href="./admin/login.php?action=logout&map="+projectData.project};
Eqwc.common.addMapFilter=function(a,b,c,d){if(a=Eqwc.common.getLayerId(a)){null==d&&(d="=");var e={};e.FILTER=a+':"'+b+'" '+d+" "+c;Map.hasOwnProperty("mergeWmsParams")&&(Map.mergeWmsParams(e),$("#panelLayer").panel("close"))}};Eqwc.common.clearMapFilters=function(){Map.hasOwnProperty("mergeWmsParams")&&(Map.mergeWmsParams({FILTER:""}),$("#panelLayer").panel("close"))};
Eqwc.common.promptForMapFilterValue=function(a,b,c,d,e,f){if(d){do if(d=prompt(c,""),null==d||""==d)break;while(isNaN(d)||parseInt(d)>f||parseInt(d)<e)}else d=prompt(c,"");null!=d&&""!=d&&Eqwc.common.addMapFilter(a,b,d)};Eqwc.common.compareQgisVersionWithInteger=function(a){var b=Eqwc.settings.qgisVersion;if(isNaN(parseFloat(b)))return"error";var c=100*parseInt(b),b=parseInt(b.split(".")[1]);if(c+b>a)return"higher";if(c+b==a)return"equal";if(c+b<a)return"lower"};
Eqwc.common.findParentRelation=function(a){var b,c,d=Object.keys(projectData.relations).length;projectData.relations.hasOwnProperty("hideJoinField")&&d--;for(var e=0;e<d;e++)if(b=Object.keys(projectData.relations)[e],c=projectData.relations[b].filter(function(b){return b.relate_layer==a})[0])return b;return!1};Eqwc.common.cleanArray=function(a){return"object"!==typeof a?a:a.filter(Boolean)};String.prototype.replaceAll=function(a,b){return this.replace(RegExp(a,"g"),b)};var UrlParams={useSSL:!1,url:"",baseUrl:"",params:{},parse:function(){var a="",a=document.documentURI?document.documentURI:window.location.href,a=a.replace(/\+/g," "),a=decodeURI(a);UrlParams.url=a;UrlParams.useSSL=UrlParams.url.match(/^https:/);a=a.split("?");UrlParams.baseUrl=a[0];if(1<a.length)for(var a=a[1].split("&"),b=0;b<a.length;b++){var c=a[b].split("=");UrlParams.params[decodeURIComponent(c[0])]=decodeURIComponent(c[1])}}};function Permalink(){this.openLogin=this.opacities=this.inactiveLayers=this.activeLayers=this.startZoom=this.startScale=this.startCenter=this.startExtent=this.initialOverlayTopics=this.initialBackgroundTopic=this.initialTopic=this.useTiledWMS=null}
Permalink.prototype={read:function(a,b){void 0!=a.tiledWms&&(this.useTiledWMS=1==a.tiledWms);void 0!=a.openLogin&&(this.openLogin="true"==a.openLogin);void 0!=a.topic&&(this.initialTopic=a.topic);void 0!=a.background&&(this.initialBackgroundTopic=a.background);void 0!=a.overlays&&(this.initialOverlayTopics=a.overlays.split(","));void 0!=a.extent&&(this.startExtent=$.map(a.extent.split(","),function(a,b){return parseFloat(a)}));void 0!=a.center&&(this.startCenter=$.map(a.center.split(","),function(a,
b){return parseFloat(a)}));void 0!=a.scale&&(this.startScale=parseFloat(a.scale));void 0!=a.zoom&&(this.startZoom=parseFloat(a.zoom));void 0!=a.activeLayers&&(this.activeLayers=a.activeLayers.split(","));void 0!=a.inactiveLayers&&(this.inactiveLayers=a.inactiveLayers.split(","));if(void 0!=a.opacities)try{this.opacities=$.parseJSON(a.opacities)}catch(c){alert("opacities:\n"+c)}void 0!=b&&b()},addOverlays:function(a,b){}};function Login(){}Login.prototype={status:function(a){a({success:!1,user:"User"})},signIn:function(a,b,c){c({success:!0,user:"User"})},signOut:function(a){a()}};function Search(){}Search.prototype={submit:function(a,b){},highlight:function(a,b){}};function Geocode(a,b,c,d,e){this.types=a;this.country=b;this.limit=c;this.provider=d;this.language=e}Geocode.prototype=new Search;Geocode.prototype.submit=function(a,b){var c=$.ajax({url:"admin/proxy.php",data:this.parseSearchParams(a),context:this});c.done(function(a,c){this.parseResults(a,c,b)});c.fail(function(a,b){alert(I18n.search.failed+"\n"+a.status+": "+a.statusText)})};
Geocode.prototype.parseSearchParams=function(a){a=$.trim(a);var b=Map.map.getView(),b=ol.proj.toLonLat(b.getCenter(),b.getProjection().getCode());return{limit:this.limit,types:this.types,country:this.country,language:this.lang,provider:this.provider,query:a,proximity:b[0]+","+b[1]}};
Geocode.prototype.parseResults=function(a,b,c){a=$.map(a.features,function(a,b){var c=a.place_name,g=new ol.geom.Point([a.geometry.coordinates[0],a.geometry.coordinates[1]]);g.transform("EPSG:4326",Map.map.getView().getProjection());var h=g.getExtent();return{name:c,bbox:h,point:g}});c([{category:null,results:a,total:a.length}])};function QgisPermalink(){}QgisPermalink.prototype=new Permalink;QgisPermalink.prototype.read=function(a,b){Permalink.prototype.read.call(this,a);""<a.startExtent&&(this.startExtent=$.map(a.startExtent.split(","),function(a,b){return parseFloat(a)}));""<a.visibleLayers&&(this.activeLayers=a.visibleLayers.split(","));""<a.visibleBackgroundLayer&&(this.initialBackgroundTopic=a.visibleBackgroundLayer);b()};function WsgiSearch(a,b,c,d){this.url=a;this.geomUrl=b;this.showHighlightLabel=c;this.searchTables=d}WsgiSearch.prototype=new Search;WsgiSearch.prototype.submit=function(a,b){var c=$.ajax({url:this.url,data:{query:$.trim(a),searchtables:this.searchTables,srs:projectData.crs.split(":")[1]},dataType:"json",context:this});c.done(function(a,c){this.parseResults(a,c,b)});c.fail(function(a,b){alert(I18n.search.failed+"\n"+a.status+": "+a.statusText)})};
WsgiSearch.prototype.parseResults=function(a,b,c){b={};for(var d=null,e=0;e<a.results.length;e++){var f=a.results[e];null==f.bbox?(d=f.displaytext,void 0===b[d]&&(b[d]=[])):b[d].push({name:f.displaytext,highlight:{searchtable:f.searchtable,displaytext:f.displaytext,showlayer:f.showlayer},bbox:f.bbox})}a=$.map(b,function(a,b){return{category:b,results:a}});c(a)};
WsgiSearch.prototype.highlight=function(a,b){var c=$.ajax({url:this.geomUrl,data:{searchtable:a.searchtable,displaytext:a.displaytext,showlayer:a.showlayer,srs:projectData.crs.split(":")[1]},dataType:"text"}),d=Eqwc.common.getLayerId(a.showlayer);d&&(Map.layers[d].visible||Map.setLayerVisible(d,!0,!0));var e=this.showHighlightLabel;c.done(function(c,d){var h=(new ol.format.WKT({splitCollection:!0})).readFeatures(c);if(e&&null!=a.displaytext)for(var l in h){var r=a.displaytext.replace(/ \([^\)]+\)$/,
"");h[l].set("labelstring",r)}l=new ol.layer.Vector({source:new ol.source.Vector({features:h}),style:function(a,b){var c=new ol.style.Stroke({color:Eqwc.settings.symbolizersHighLightLayer.Line.strokeColor,width:Eqwc.settings.symbolizersHighLightLayer.Line.strokeWidth}),d=new ol.style.Fill({color:"rgba(255, 140, 0, 0)"}),e=null;a.get("labelstring")&&(e=new ol.style.Text({text:a.get("labelstring"),textAlign:"center",textBaseline:"bottom",offsetY:-5,font:"normal 16px Helvetica,Arial,sans-serif",fill:new ol.style.Fill({color:"rgba(0, 0, 0, 1.0)"}),
stroke:new ol.style.Stroke({color:"rgba(255, 255, 255, 1.0)",width:2})}));return[new ol.style.Style({image:new ol.style.Circle({radius:4,fill:d,stroke:c}),fill:d,stroke:c,text:e})]}});l.name="highlight";h=h[0].getGeometry().getExtent();Map.zoomToExtent(h,Config.map.minScaleDenom.search);b(l)})};var Config={parseExtentToArray:function(a){var b=[];a=a.split(",");b.push(parseInt(a[0]));b.push(parseInt(a[1]));b.push(parseInt(a[2]));b.push(parseInt(a[3]));return b},extractStringFromObject:function(a,b){if(!b)return null;if(-1==b.indexOf(a))return b;var c="",c=b.indexOf("(")+1,d=b.indexOf(")");return c="["+b.substring(c,d)+"]"},getLayerName:function(a){return projectData.layers[a]?projectData.use_ids?projectData.layers[a].layername:a:a},getBaseLayerName:function(a){var b=projectData.baseLayers(),
c;for(c in b)if(b[c].title==a)return b[c].name;return!1},baseLayerExists:function(a){var b=projectData.baseLayers(),c;for(c in b)if(b[c].title==a)return!0;return!1},extraLayerExists:function(a){var b=projectData.extraLayers(),c;for(c in b)if(b[c].title==a)return!0;return!1},debug:!1,gui:{hideShareButton:!0,hideLoginButton:!1,useLayertreeGroupCheckboxes:!0}};Config.login=new Login;Config.sslLogin=!1;Config.data={};Config.data.initialTopic=projectData.project;
Config.defaultProperties={following:!0,orientation:!1,scalebar:!0};Config.featureInfo={};Config.featureInfo.format="text/xml";Config.featureInfo.useWMSGetFeatureInfo=!0;Config.featureInfo.wmsMaxFeatures=Eqwc.settings.limitSearchMaxResults?Eqwc.settings.limitSearchMaxResults:null;
Config.featureInfo.tolerances={point:Eqwc.settings.featureInfoTolerances&&Eqwc.settings.featureInfoTolerances.point?Eqwc.settings.featureInfoTolerances.point:4,line:Eqwc.settings.featureInfoTolerances&&Eqwc.settings.featureInfoTolerances.line?Eqwc.settings.featureInfoTolerances.line:4,polygon:Eqwc.settings.featureInfoTolerances&&Eqwc.settings.featureInfoTolerances.polygon?Eqwc.settings.featureInfoTolerances.polygon:2};Config.map={};Config.map.dpi=96;Config.map.extent=Config.parseExtentToArray(projectData.extent);
Config.map.init={center:ol.extent.getCenter(Config.map.extent),zoom:6};""==projectData.crs&&(alert("Map CRS must be set in QGIS!"),Eqwc.settings.useGisPortal?window.location.href=Eqwc.settings.gisPortalRoot:window.location.href="/");Config.map.projectionList=[];Config.map.projectionList.push([projectData.crs,projectData.crs_description]);
if(void 0===proj4.defs[projectData.crs]){proj4.defs(projectData.crs,projectData.proj4);var projDef=CustomProj[projectData.crs];Config.map.projection=new ol.proj.Projection({code:projectData.crs,extent:projDef.extent,units:projDef.units,axisOrientation:!1===projDef.yx?"enu":"neu"})}else Config.map.projection=ol.proj.get(projectData.crs);
for(var j=0;j<projectData.crs_list.length;j++){var code=projectData.crs_list[j],title=code;void 0===proj4.defs[code]&&proj4.defs(code,Proj4js.defs[code]);void 0!==proj4.defs[code]&&(title=proj4.defs[code].title?proj4.defs[code].title:code,code!=projectData.crs&&Config.map.projectionList.push([code,title]))}Config.map.viewOptions={projection:Config.map.projection,extent:projectData.restrictToStartExtent?Config.map.extent:void 0};Config.data.baselayers=[];
if(null!==projectData.baseLayers())for(var i=0;i<projectData.baseLayers().length;i++){var bl=projectData.baseLayers()[i];"Google"!=bl.type&&Config.data.baselayers.push(bl);"WMTS"==bl.type&&(Config.map.viewOptions.resolutions=$.parseJSON(bl.definition).resolutions)}Config.data.extralayers=projectData.extraLayers();Config.data.wfslayers={};Config.data.gotolayers={};Config.map.wmsServerType="qgis";
Config.map.wmsParams={FORMAT:"image/png; mode=8bit",TRANSPARENT:null==projectData.baseLayers()&&null==projectData.extraLayers()?!1:!0};Config.map.useTiledBackgroundWMS=!0;Config.map.useTiledOverlayWMS=!1;Config.map.minScaleDenom={map:5E3,geolocation:null,search:5E3};Config.map.initialGeolocationMaxScale=2E3;var sCon=projectData.geoCode?projectData.geoCode:null;null!=sCon&&(Config.search=new Geocode(sCon.layers,sCon.country,10,sCon.provider,projectData.lang));
null==sCon&&projectData.wsgi&&(Config.search=new WsgiSearch("/wsgi/search.wsgi","/wsgi/getSearchGeom.wsgi",!1,projectData.wsgi.searchtables));Config.mapfishSearchUrl=function(a){return"data/mapfish_search_response.json"};Config.mapfishParseFeature=function(a){return{category:a.kategorie,name:a.begriff,highlight:{fid:a.fid,layer:"FullSearch"+a.kategorie},bbox:[a.bbox_xmin,a.bbox_ymin,a.bbox_xmax,a.bbox_ymax]}};Config.mapfishHighlightWmsUrl="/wms/FullSearch";
Config.mapfishLocateUrl=function(a,b){return"/locate/"+a+"?"+$.param({locations:b})};Config.permalink=new QgisPermalink;Config.print={hires:!1,dpi:300};Config.customInitViewer=function(){};
function sendMail(a,b,c,d,e){var f={};f.mailto=a;f.subject=b;f.body=c;f.template="";e&&(f.template=e);""<Eqwc.settings.mailServiceUrl&&$.ajax({url:Eqwc.settings.mailServiceUrl,data:f,type:"POST",dataType:"text",timeout:1E3,context:this}).done(function(a,b,c){d||alert(TR.feedbackSuccessTitle+"<br>"+TR.feedbackSuccessMsg)}).fail(function(a,b,c){d||alert(TR.feedbackErrorTitle+"<br>"+TR.feedbackErrorMsg)})};function Progress(){this.loaded=this.loading=0}Progress.prototype.addLoading=function(){0===this.loading&&this.show();++this.loading;this.update()};Progress.prototype.addLoaded=function(){++this.loaded;this.update()};Progress.prototype.update=function(){this.loading===this.loaded?(this.loaded=this.loading=0,this.hide()):1<this.loading?this.show(I18n.properties.mapLoading+this.loaded+"/"+this.loading):this.show(I18n.properties.mapLoading)};
Progress.prototype.show=function(a){!1===$("#panelLayer").hasClass("ui-panel-open")&&(null!==Map.geolocation&&Map.geolocation.getTracking()&&Gui.following||$.mobile.loading("show",{textVisible:!0,text:a,theme:"c"}))};Progress.prototype.hide=function(){this.loading===this.loaded&&$.mobile.loading("hide")};var Map={};Map.progress=new Progress;Map.topics={};Map.topic=null;Map.layers={};Map.backgroundTopic=null;Map.backgroundLayers={};Map.map=null;Map.minResolution=null;Map.topicLayer=null;
Map.backgroundLayer=null;Map.selectionLayer=null;Map.redliningLayer=null;Map.highlightLayer=null;Map.geolocationLayer=null;Map.overlayLayers={};Map.geolocation=null;Map.deviceOrientation=null;Map.windowOrientation=void 0;Map.scaleLine=null;Map.lastClickPos=null;Map.clickMarker=null;Map.ignoreClick=!1;Map.singleClickHandlers={};Map.alertMessages={};Map.useTiledWMS=Eqwc.settings.mobileUseTiledWMS;Map.userCrs=null;
Map.userCrsTitle=function(){return Config.map.projectionList.filter(function(a){return a[0]==Map.userCrs})[0][1]};
Map.createMap=function(){null!=Config.permalink.useTiledWMS&&(Map.useTiledWMS=Config.permalink.useTiledWMS);Map.map=new ol.Map({layers:[],target:"map",view:new ol.View(Config.map.viewOptions),controls:[]});Map.map.getView().fit(Config.map.extent,Map.map.getSize());Map.map.getView().on("change:rotation",function(){$.event.trigger({type:"maprotation",rotation:Map.map.getView().getRotation()})});Map.setMinScaleDenom(Config.map.minScaleDenom.map);Map.map.getView().on("change:resolution",function(){Map.map.getView().getResolution()<
Map.minResolution&&Map.map.getView().setResolution(Map.minResolution)});Map.map.on("singleclick",function(a){if(!Map.ignoreClick){Map.lastClickPos=a.coordinate;for(var b in Map.singleClickHandlers){var c=Map.singleClickHandlers[b];c.isActive()&&c.handleEvent(a)}}});Map.map.on("movestart",Map.userMoves)};
Map.clearLayers=function(){Map.map.getLayers().clear();Map.topicLayer=null;Map.backgroundLayer=null;Map.backgroundTopic=null;Map.backgroundLayers={};Map.selectionLayer=null;Map.redliningLayer=null;Map.highlightLayer=null;Map.overlayLayers={}};
Map.setTopicLayer=function(){function a(a){!1==a?Eqwc.common.redirect():(Map.showAlert("c"),Map.setAlertMsg("qgis","image load error"))}var b=$.extend({},Config.map.wmsParams,{LAYERS:Map.visibleLayers().join(","),OPACITIES:Map.layerOpacities()});Map.backgroundTopic&&(b.TRANSPARENT=!0);var c=null,b={url:Map.topics[Map.topic].wms_url,params:b,serverType:Config.map.wmsServerType,dpi:Config.map.dpi};Map.topicLayer=null;Map.useTiledWMS?(c=new ol.source.TileWMS(b),c.on("tileloaderror",function(a){console.log("tile error")}),
Map.topicLayer=new ol.layer.Tile({source:c})):(b.ratio=1,c=new ol.source.ImageWMS(b),c.on("imageloadstart",function(){Map.progress.addLoading()}),c.on("imageloadend",function(){Map.progress.addLoaded();Map.hideAlert();Map.clearAlertMsg("qgis")}),c.on("imageloaderror",function(){Map.progress.addLoaded();$.ajax({url:"./admin/login.php?action=status",dataType:"text",timeout:1E3}).done(function(b,c,f){"success"==c?a(1==b):a(!0)}).fail(function(b,c,f){a(!0)})}),Map.topicLayer=new ol.layer.Image({source:c}));
Map.topicLayer.name="topic";Map.map.addLayer(Map.topicLayer);Map.map.addLayer(Map.measurementLayer)};
Map.setBackgroundLayer=function(a,b,c){a=c?Config.data.baselayers[b]:Config.data.extralayers[b];var d={};b=0==b&&c&&Eqwc.settings.visibleFirstBaseLayer?!0:!1;switch(a.type){case "OSM":c=$.parseJSON(a.definition);d=new ol.layer.Tile({visible:b,opacity:c.opacity,source:new ol.source.OSM});break;case "XYZ":c=$.parseJSON(a.definition);d=new ol.layer.Tile({visible:b,opacity:c.options.opacity,source:new ol.source.XYZ(c)});break;case "Bing":c=$.parseJSON(a.definition);d=new ol.layer.Tile({visible:b,preload:Infinity,
source:new ol.source.BingMaps({key:c.key,imagerySet:c.imagerySet})});break;case "WMTS":c=$.parseJSON(a.definition);for(var d=[],e=[],f="string"==typeof c.serverResolutions?JSON.parse(c.serverResolutions):c.serverResolutions,g=Config.map.projection.getExtent(),h=ol.extent.getWidth(g)/256,l=void 0!==f?f.length:eval(c.numZoomLevels),r,g=Config.extractStringFromObject("OpenLayers",c.maxExtent),n=0;n<l;++n)d[n]=n,e[n]=h/Math.pow(2,n);void 0!==c.matrixIds&&(d=eval(c.matrixIds));void 0!==c.origins&&(r=JSON.parse(c.origins));
void 0!==f&&(e=f);f=b;b||void 0==c.visibility||(f=c.visibility);d=new ol.layer.Tile({visible:f,opacity:c.opacity,extent:projectData.restrictToStartExtent?projectData.extent.split(","):void 0,source:new ol.source.WMTS({url:c.url,layer:c.layer,matrixSet:c.matrixSet,requestEncoding:c.requestEncoding,style:c.style,projection:Config.map.projection,format:c.format,tileGrid:new ol.tilegrid.WMTS({extent:JSON.parse(g),resolutions:e,matrixIds:d,origins:r})})});break;case "WMS":c=$.parseJSON(a.definition),f=
b,b||void 0==c.visibility||(f=c.visibility),d=new ol.layer.Tile({visible:f,opacity:c.options.opacity,source:new ol.source.TileWMS({url:c.url,params:c.params})})}d.name=a.name;Map.map.getLayers().insertAt(0,d);Map.backgroundLayers[d.name]=d};Map.clearOverlayLayers=function(){for(var a in Map.overlayLayers)Map.map.removeLayer(a);Map.overlayLayers={}};
Map.addOverlayLayer=function(a,b){var c=$.extend({},Config.map.wmsParams,{LAYERS:b.join(","),TRANSPARENT:!0}),c={url:Map.topics[a].wms_url,params:c,extent:Config.map.extent,serverType:Config.map.wmsServerType,dpi:Config.map.dpi},d=null,d=Config.map.useTiledOverlayWMS?new ol.layer.Tile({source:new ol.source.TileWMS(c)}):new ol.layer.Image({source:new ol.source.ImageWMS(c)});d.name="overlay_"+a;void 0!=Map.overlayLayers[a]&&Map.map.removeLayer(Map.overlayLayers[a]);Map.overlayLayers[a]=d;Map.map.addLayer(d)};
Map.toggleOverlayLayer=function(a,b){void 0!=Map.overlayLayers[a]&&Map.overlayLayers[a].setVisible(b)};Map.setSelectionLayer=function(a){null!=Map.selectionLayer&&(Map.map.removeLayer(Map.selectionLayer),Map.selectionLayer=null);null!=a&&(Map.selectionLayer=a,Map.map.addLayer(Map.selectionLayer))};Map.toggleSelectionLayer=function(a){null!=Map.selectionLayer&&Map.selectionLayer.setVisible(a)};
Map.setRedliningLayer=function(a){null!=Map.redliningLayer&&(Map.map.removeLayer(Map.redliningLayer),Map.redliningLayer=null);null!=a&&(Map.redliningLayer=a,Map.map.addLayer(Map.redliningLayer))};Map.toggleRedliningLayer=function(a){null!=Map.redliningLayer&&Map.redliningLayer.setVisible(a)};Map.setHighlightLayer=function(a){null!=Map.highlightLayer&&(Map.map.removeLayer(Map.highlightLayer),Map.highlightLayer=null);null!=a&&(Map.highlightLayer=a,Map.map.addLayer(Map.highlightLayer))};
Map.setLayerVisible=function(a,b,c){Map.layers[a].visible=b;c&&Map.mergeWmsParams({LAYERS:Map.visibleLayers().join(",")})};Map.visibleLayers=function(){var a=[],b;for(b in Map.layers)Map.layers[b].visible&&(projectData.use_ids?a.push(Map.layers[b].id):a.push(Map.layers[b].title));return a};
Map.featureInfoLayers=function(){var a=[],b=Map.map.getView().getResolution(),c;for(c in Map.layers){var d=Map.layers[c];if(d.visible&&d.identify){var e=!0;void 0!=d.minscale&&(e=b>=Map.scaleDenomToResolution(d.minscale,!1));e&&void 0!=d.maxscale&&(e=b<=Map.scaleDenomToResolution(d.maxscale,!1));e&&a.push(c)}}if(b=Eqwc.settings.replaceIdentifyLayerWithView)for(c=0;c<b.length;c++){if(e=d=Eqwc.common.getLayerId(b[c]))e=Eqwc.common.getIdentifyLayerName(d),e=Eqwc.common.getLayerId(e);d=a.indexOf(d);-1<
d&&(a[d]=e)}return a};Map.getGetFeatureInfoUrl=function(a,b){var c=Map.map.getView();return Map.topicLayer.getSource().getGetFeatureInfoUrl(a,c.getResolution(),c.getProjection(),b)};Map.setLayerTransparency=function(a,b,c){Map.layers[a].transparency=b;c&&Map.mergeWmsParams({OPACITIES:Map.layerOpacities()})};
Map.layerOpacities=function(){var a=[],b=!1,c;for(c in Map.layers)if(Map.layers[c].visible){var d=Math.round((100-Map.layers[c].transparency)/100*255);a.push(d);b=b||255!=d}return b?a.join(","):null};Map.refresh=function(){var a=Map.visibleLayers();0<a.length&&Map.mergeWmsParams({LAYERS:a.join(","),OPACITIES:Map.layerOpacities()});Map.topicLayer.setVisible(0<a.length)};Map.redraw=function(){Map.mergeWmsParams({t:(new Date).getTime()})};
Map.mergeWmsParams=function(a){var b=Map.topicLayer.getSource();a=$.extend({},b.getParams(),a);b.updateParams(a)};Map.setRotation=function(a){Map.map.getView().setRotation(a)};Map.scaleDenomToResolution=function(a,b){var c=a/(Map.map.getView().getProjection().getMetersPerUnit()*(Config.map.dpi/0.0254));return b?Map.map.getView().constrainResolution(c):c};Map.setMinScaleDenom=function(a){Map.minResolution=Map.scaleDenomToResolution(a,!0);Map.clampToScale(a)};
Map.clampToScale=function(a){a=Map.scaleDenomToResolution(a,!0);Map.map.getView().getResolution()<a&&Map.map.getView().setResolution(a)};Map.zoomToExtent=function(a,b){Map.map.getView().fit(a,Map.map.getSize());null!=b&&Map.clampToScale(b)};Map.setCenter=function(a){Map.map.getView().setCenter(a)};Map.setScale=function(a){a=Map.scaleDenomToResolution(a,!0);Map.map.getView().setResolution(a)};Map.setZoom=function(a){Map.map.getView().setZoom(a)};
Map.updateAndroidLocation=function(a){Map.geolocation.setLocation(a,Gui.tracking)};
Map.toggleTracking=function(a){if(null==Map.geolocation){"undefined"==typeof Android?(Map.geolocation=new ol.Geolocation({projection:Map.map.getView().getProjection(),trackingOptions:{enableHighAccuracy:!0,maximumAge:0,timeout:3E3}}),Map.geolocation.set("source","Geolocation API")):(Map.geolocation=new ol.AndroidLocation({projection:Map.map.getView().getProjection()}),Map.geolocation.set("source","Android API"));var b=parseFloat(0<$("#antennaHeight").length?$("#antennaHeight")[0].value:0);isNaN(b)&&
(b=0);var c=0,d="";"function"==typeof Editor&&(c=mobEditor.getAntennaOffset(),b+=c,d=mobEditor.getAntennaType());Map.geolocation.setProperties({altCorrection:0,altCorrectionSource:"",antenna:b,antennaOffset:c,antennaType:d});Map.geolocation.on("error",function(a){a.code==Eqwc.geolocationErrors.TIMEOUT?(Map.geolocation.setTracking(!1),Map.geolocation.setTracking(!0)):(""<a.message?alert(a.message):alert(I18n.geolocation.permissionDeniedMessage),$("#btnLocation .ui-icon").toggleClass("ui-icon-location_on",
!1),$("#btnLocation .ui-icon").toggleClass("ui-icon-location_off",!0),Gui.tracking=!1,Gui.showLocationPanel(!1),$("#locationMarker").toggle(!1),Map.geolocationLayer.setVisible(!1))});Map.geolocation.on("change",function(){var a=Map.geolocation.getPosition();f.setPosition(a);Gui.showLocationPanel(!0);"function"==typeof Editor&&(mobEditor.showEditPanel(!0),"function"==typeof Record&&mobRecord.layer&&mobRecord.updateRecording(),mobGoto&&mobGoto.feature&&mobGoto.updateGotoContent());$("#btnInfo").show();
Map.geolocationLayer.setVisible(!0)});var e=new ol.Feature;e.setStyle(new ol.style.Style({fill:new ol.style.Fill({color:"rgba(255, 0, 0, 0.05)"})}));var f=new ol.Overlay({element:$('<div id="locationMarker" class="locationMarkerNormal"></div>')[0],positioning:"center-center",stopEvent:!1});Map.geolocation.on("change:accuracy",function(){var a=Map.geolocation.getAccuracy(),b=$("#locationMarker");"function"==typeof Editor&&(a<EditorConfig.accuracyLimit?(b.addClass("locationMarkerGood").removeClass("locationMarkerNormal"),
e.setStyle(new ol.style.Style({fill:new ol.style.Fill({color:"rgba(0, 255, 0, 0.05)"})}))):(b.addClass("locationMarkerNormal").removeClass("locationMarkerGood"),e.setStyle(new ol.style.Style({fill:new ol.style.Fill({color:"rgba(255, 0, 0, 0.05)"})}))))});Map.geolocation.on("change:accuracyGeometry",function(){e.setGeometry(Map.geolocation.getAccuracyGeometry())});Map.geolocation.once("change:position",Map.initialCenterOnLocation);Map.geolocationLayer=new ol.layer.Vector({source:new ol.source.Vector({features:[e]})});
Map.geolocationLayer.name="geolocation";Map.map.addLayer(Map.geolocationLayer);Map.map.addOverlay(f)}Map.geolocation.setTracking(a);$("#locationMarker").toggle(a);a||(Gui.showLocationPanel(!1),"function"==typeof Editor&&(mobEditor.showEditPanel(!1),"function"==typeof Record&&mobRecord.showRecordPanel(!1)),$("#btnInfo").hide(),Map.geolocationLayer.setVisible(!1))};
Map.toggleFollowing=function(a){if(null!=Map.geolocation)if(Gui.following=a)Map.geolocation.on("change:position",Map.centerOnLocation);else Map.geolocation.un("change:position",Map.centerOnLocation),$("#btnLocation .ui-icon").toggleClass("ui-icon-location_on",!1),$("#btnLocation .ui-icon").toggleClass("ui-icon-location_out",!0)};
Map.initialCenterOnLocation=function(){var a=Map.geolocation.getPosition(),b=Map.map.getView();if(null!=Config.map.initialGeolocationMaxScale){var c=Map.scaleDenomToResolution(Config.map.initialGeolocationMaxScale,!0);Map.map.getView().getResolution()>c?(b.set("appMove",!0),b.animate({center:a,resolution:c})):(b.set("appMove",!0),b.animate({center:a}))}else b.set("appMove",!0),b.animate({center:a});"function"==typeof Editor&&(EditorConfig.altCorrectionLayer&&mobEditor.getHeightCorrection(),"function"==
typeof Record&&mobRecord.showRecordPanel(!0));Map.geolocation.un("change:position",Map.initialCenterOnLocation)};Map.centerOnLocation=function(){var a=Map.map.getView(),b=a.getCenter(),c=Map.geolocation.getPosition(),d=Math.abs(b[0]-c[0]),b=Math.abs(b[1]-c[1]),e=Map.map.getView().calculateExtent();if(d>ol.extent.getWidth(e)/4||b>ol.extent.getHeight(e)/4)a.set("appMove",!0),a.animate({center:c}),Map.clampToScale(Config.map.minScaleDenom.geolocation)};
Map.userMoves=function(){var a=Map.map.getView(),b=a.get("appMove")||!1;a.unset("appMove");!b&&Map.geolocation&&Gui.tracking&&Map.toggleFollowing(!1)};Map.setWindowOrientation=function(a){Map.windowOrientation=a;null!=Map.deviceOrientation&&Map.deviceOrientation.getTracking()&&void 0!=Map.deviceOrientation.getHeading()&&Map.setRotation(Map.adjustedHeading(-Map.deviceOrientation.getHeading()))};Map.adjustedHeading=function(a){void 0!=Map.windowOrientation&&(a-=Map.windowOrientation*Math.PI/180);return a};
Map.toggleOrientation=function(a){null==Map.deviceOrientation&&(Map.deviceOrientation=new ol.DeviceOrientation,Map.deviceOrientation.on("change:heading",function(a){a=Map.adjustedHeading(-a.target.getHeading());0.0175<Math.abs(Map.map.getView().getRotation()-a)&&Map.setRotation(a)}));Map.deviceOrientation.setTracking(a)};
Map.toggleClickMarker=function(a){null==Map.clickMarker&&(Map.clickMarker=new ol.Overlay({element:$('<div id="clickMarker"></div>')[0],positioning:"center-center",stopEvent:!1}),Map.map.addOverlay(Map.clickMarker));Map.clickMarker.setPosition(a?Map.lastClickPos:void 0)};
Map.toggleScalebar=function(a){if(null==Map.scaleLine){var b=Eqwc.settings.measurementsUnitSystem?Eqwc.settings.measurementsUnitSystem:"metric";"english"==b.toLowerCase()?b="us":"geographic"==b.toLowerCase()&&(b="degrees");Map.scaleLine=new ol.control.ScaleLine({units:b})}a&&null==Map.scaleLine.getMap()?Map.map.addControl(Map.scaleLine):Map.map.removeControl(Map.scaleLine)};Map.toggleClickHandling=function(a){Map.ignoreClick=!a};Map.registerClickHandler=function(a,b){Map.singleClickHandlers[a]=b};
Map.unregisterClickHandler=function(a){Map.singleClickHandlers[a]&&(Map.singleClickHandlers[a].toggle(!1),delete Map.singleClickHandlers[a])};Map.activateClickHandler=function(a){for(var b in Map.singleClickHandlers)Map.singleClickHandlers[b].toggle(!1);null!=a&&Map.singleClickHandlers[a]&&Map.singleClickHandlers[a].toggle(!0)};
Map.featureInfoOnLocation=function(){var a=Map.geolocation.getPosition();(new FeatureInfo(Gui.showFeatureInfoResults)).callOnLocation(a,Config.featureInfo.useWMSGetFeatureInfo,null);Map.lastClickPos=a};Map.openNavigation=function(){var a=(new ol.geom.Point(Map.lastClickPos)).transform(projectData.crs,"EPSG:4326"),b={};b.destination=a.getCoordinates().reverse().toString();window.open("https://www.google.com/maps/dir/?api=1&"+$.param(b),"_blank")};Map.showAlert=function(a){$("#btnAlert").buttonMarkup({theme:a}).show()};
Map.hideAlert=function(){$("#btnAlert").hide()};Map.setAlertMsg=function(a,b){this.alertMessages[a]=b};Map.clearAlertMsg=function(a){delete this.alertMessages[a]};
Map.loadHiddenIcons=function(){$("#btnLocation .ui-icon").addClass("ui-icon-location_on");$("#btnCompass").show();$("#btnCompass").hide();this.showAlert("c");this.hideAlert();$("#btnAdd").show();$("#btnAdd").hide();$("#btnRemove").show();$("#btnRemove").hide();$("#btnRecord").show();$("#btnRecord").hide();$("#btnRecordStop").show();$("#btnRecordStop").hide();$("#btnEnd").show();$("#btnEnd").hide();$("#btnGotoPage").show();$("#btnGotoPage").hide();$("#btnLocation .ui-icon").removeClass("ui-icon-location_on")};
Map.formatLength=function(a){a=ol.Sphere.getLength(a);if(0===a)return $(".tooltip-measure").hide(),null;a=1E3<a?Math.round(a/1E3*100)/100+" km":Math.round(100*a)/100+" m";$(".tooltip-measure").show();return a};Map.formatArea=function(a){a=ol.Sphere.getArea(a);if(0===a)return $(".tooltip-measure").hide(),null;a=1E6<=a?Math.round(a/1E6*100)/100+" km<sup>2</sup>":1E6>a&&1E4<=a?Math.round(a/1E4*100)/100+" ha":Math.round(100*a)/100+" m<sup>2</sup>";$(".tooltip-measure").show();return a};
Map.createMeasureTooltip=function(){Map.measureTooltipElement&&Map.measureTooltipElement.parentNode.removeChild(Map.measureTooltipElement);Map.measureTooltipElement=document.createElement("div");Map.measureTooltipElement.className="tooltip tooltip-measure";Map.measureTooltip=new ol.Overlay({element:Map.measureTooltipElement,offset:[0,-15],positioning:"bottom-center"});Map.measureTooltip.set("measure",!0);Map.map.addOverlay(Map.measureTooltip)};
Map.measurementLayer=new ol.layer.Vector({source:new ol.source.Vector,style:new ol.style.Style({fill:new ol.style.Fill({color:"rgba(255, 255, 255, 0.2)"}),stroke:new ol.style.Stroke({color:"#ffcc33",width:2}),image:new ol.style.Circle({radius:7,fill:new ol.style.Fill({color:"#ffcc33"})})})});
Map.startMeasuring=function(){Map.measurementSketch=new ol.interaction.Draw({clickTolerance:1,source:Map.measurementLayer.getSource(),type:"off"==$("#measureArea").val()?"LineString":"Polygon",style:new ol.style.Style({fill:new ol.style.Fill({color:"rgba(255, 255, 255, 0.2)"}),stroke:new ol.style.Stroke({color:"rgba(0, 0, 0, 0.5)",lineDash:[10,10],width:2}),image:new ol.style.Circle({radius:5,stroke:new ol.style.Stroke({color:"rgba(0, 0, 0, 0.7)"}),fill:new ol.style.Fill({color:"rgba(255, 255, 255, 0.2)"})})})});
Map.measurementActive=!0;$("#measurePanel").show();$("#btnMeasureStop").show();$("#btnMeasure").hide();Map.toggleClickHandling(!1);Map.createMeasureTooltip();Map.measurementSketch.on("drawstart",function(a){$("#btnMeasureFinish").show();$("#btnMeasureRemove").show();sketch=a.feature;var b=a.coordinate;listener=sketch.getGeometry().on("change",function(a){a=a.target;var d;0===a.getCoordinates().length?(Map.measureTooltipElement.parentNode.setAttribute("hidden",!0),Map.measurementSketch.dispatchEvent({type:"drawend"})):
(a instanceof ol.geom.Polygon?(d=Map.formatArea(a),b=a.getInteriorPoint().getCoordinates()):a instanceof ol.geom.LineString&&(d=Map.formatLength(a),b=a.getLastCoordinate()),Map.measureTooltipElement.innerHTML=d,Map.measureTooltip.setPosition(b))})},this);Map.measurementSketch.on("drawend",function(){$("#btnMeasureFinish").hide();$("#btnMeasureRemove").hide();Map.measureTooltipElement.className="tooltip tooltip-static";Map.measureTooltip.setOffset([0,-7]);sketch=null;Map.measureTooltipElement=null;
Map.createMeasureTooltip();ol.Observable.unByKey(listener)},this);Map.map.addInteraction(Map.measurementSketch)};Map.stopMeasuring=function(){Map.measurementActive=!1;Map.map.getOverlays().getArray().slice(0).forEach(function(a){a.get("measure")&&Map.map.removeOverlay(a)});$("#measurePanel").hide();$("#btnMeasureStop").hide();$("#btnMeasureRemove").hide();$("#btnMeasureFinish").hide();$("#btnMeasure").show();Map.toggleClickHandling(!0);Map.map.removeInteraction(Map.measurementSketch);Map.measurementLayer.getSource().clear()};
Map.finishMeasuringSketch=function(){Map.measurementSketch.finishDrawing()};Map.removeLastMeasurePoint=function(){Map.measurementSketch.removeLastPoint()};function MapClickHandler(){this.active=!1}MapClickHandler.prototype={toggle:function(a){this.active=a},isActive:function(){return this.active},handleEvent:function(a){}};function FeatureInfo(a){this.resultsCallback=a}FeatureInfo.prototype=new MapClickHandler;
FeatureInfo.prototype.callOnLocation=function(a,b,c){var d=null;c=null===c?Map.featureInfoLayers():c;Map.toggleClickHandling(!1);b?(b={INFO_FORMAT:Config.featureInfo.format,FEATURE_COUNT:Config.featureInfo.wmsMaxFeatures},"qgis"===Config.map.wmsServerType&&$.extend(b,{FI_POINT_TOLERANCE:Config.featureInfo.tolerances.point,FI_LINE_TOLERANCE:Config.featureInfo.tolerances.line,FI_POLYGON_TOLERANCE:Config.featureInfo.tolerances.polygon,QUERY_LAYERS:c.join(",")}),d=Map.getGetFeatureInfoUrl(a,b)):(b=Map.map.getView(),
d=hiddenProject.getSource().getGetFeatureInfoUrl(a,b.getResolution(),b.getProjection(),{INFO_FORMAT:Config.featureInfo.format,QUERY_LAYERS:c}));$.ajax({url:d,dataType:"text",timeout:5E3,context:this}).done(function(a,b,c){c=null;c="text/xml"===Config.featureInfo.format?this.parseResults([a]):[a];this.resultsCallback(b,c,200);Map.toggleClickHandling(!0)}).fail(function(a,b,c){a.responseText?this.resultsCallback(b,a.responseText,a.status):this.resultsCallback(b,c,0);Map.toggleClickHandling(!0)})};
FeatureInfo.prototype.filter=function(a,b){Map.toggleClickHandling(!1);$.ajax({url:Map.topics[Map.topic].wms_url,data:{SERVICE:"WMS",VERSION:ol.DEFAULT_WMS_VERSION,REQUEST:"GetFeatureInfo",FORMAT:"image/png",INFO_FORMAT:Config.featureInfo.format,QUERY_LAYERS:b,LAYERS:b,FILTER:a,FEATURE_COUNT:Eqwc.settings.limitAttributeFeatures},dataType:"text",timeout:5E3,context:this}).done(function(a,b,e){e=null;e="text/xml"===Config.featureInfo.format?this.parseResults([a]):[a];this.resultsCallback(b,e,200);Map.toggleClickHandling(!0)}).fail(function(a,
b,e){this.resultsCallback(b,e,0);Map.toggleClickHandling(!0)})};
FeatureInfo.prototype.handleEvent=function(a){var b=null,b=Map.featureInfoLayers();Map.toggleClickHandling(!1);if(Config.featureInfo.useWMSGetFeatureInfo){var c={INFO_FORMAT:Config.featureInfo.format,FEATURE_COUNT:Config.featureInfo.wmsMaxFeatures};"qgis"===Config.map.wmsServerType&&$.extend(c,{FI_POINT_TOLERANCE:Math.round(Config.featureInfo.tolerances.point*a.frameState.pixelRatio),FI_LINE_TOLERANCE:Math.round(Config.featureInfo.tolerances.line*a.frameState.pixelRatio),FI_POLYGON_TOLERANCE:Math.round(Config.featureInfo.tolerances.polygon*
a.frameState.pixelRatio),QUERY_LAYERS:b.join(","),WITH_MAPTIP:!0});b=Map.getGetFeatureInfoUrl(a.coordinate,c)}else b=Config.featureInfo.url(Map.topic,a.coordinate,b);$.ajax({url:b,dataType:"text",timeout:3E3,context:this,beforeSend:function(){this.loading("show")}}).done(function(a,b){this.loading("hide");var c=null,c="text/xml"===Config.featureInfo.format?this.parseResults([a]):[a];this.resultsCallback(b,c,200);Map.toggleClickHandling(!0)}).fail(function(a,b,c){this.loading("hide");a.responseText?
this.resultsCallback(b,a.responseText,a.status):this.resultsCallback(b,c,0);Map.toggleClickHandling(!0)})};
FeatureInfo.prototype.parseResults=function(a){for(var b=[],c=0;c<a.length;c++){var d=$.parseXML(a[c]);$(d).find("Layer").each(function(){var a=[],c=$(this).attr("name");if(0<$(this).find("Feature").length)$(this).find("Feature").each(function(){var b=[];$(this).find("Attribute").each(function(){"geometry"!=$(this).attr("name")&&b.push({name:$(this).attr("name"),value:$(this).attr("value").replace(/null/ig,Eqwc.settings.noDataValue)})});a.push({id:$(this).attr("id"),attributes:b})});else if(0<$(this).find("Attribute").length){var d=
[];$(this).find("Attribute").each(function(){d.push({name:Eqwc.common.getRasterFieldName(Config.getLayerName(c),$(this).attr("name")),value:$(this).attr("value").replace(/null/ig,Eqwc.settings.noDataValue)})});a.push({id:null,attributes:d})}0<a.length&&b.push({layer:c,features:a})})}return b.reverse()};FeatureInfo.prototype.loading=function(a){setTimeout(function(){$.mobile.loading(a)},1)};var Topics={loadTopics:function(a,b){var c=[{name:projectData.project,title:projectData.title,icon:projectData.client_logo,categorytitle:projectData.client_display_name,categorysort:0,categories_topics_sort:0,wms_url:"/proxy/"+projectData.project,background_layer:!1,minscale:Eqwc.settings.mobileMinScale?Eqwc.settings.mobileMinScale:100}];categories={};for(var d=0;d<c.length;d++){var e=c[d];void 0===categories[e.categorytitle]&&(categories[e.categorytitle]=[]);categories[e.categorytitle].push(e)}var c=
[],f;for(f in categories)categories.hasOwnProperty(f)&&(d=categories[f].sort(function(a,b){var c=a.categories_topics_sort-b.categories_topics_sort;if(0===c)c=a.title.localeCompare(b.title);else if(null===a.categories_topics_sort||null===b.categories_topics_sort)c=-c;return c}),c.push({title:f,topics:d}));b(c)}};var Layers={markerPrefix:"____",loadLayers:function(a,b){var c=projectData.layers;groups={};for(var d in c){var e=c[d];e.wfs&&(Config.data.wfslayers[d]=e.layername);e.goto&&(Config.data.gotolayers[d]=e.layername);null===e.groupname&&(e.groupname=Layers.markerPrefix+e.layername);e.parent&&void 0===groups[e.parent]&&(groups[e.parent]=[]);void 0===groups[e.groupname]&&(groups[e.groupname]=[]);groups[e.groupname].push(e)}var c=[],f;for(f in groups)groups.hasOwnProperty(f)&&c.push({title:f,parent:0<groups[f].length?
groups[f][0].parent:null,layers:groups[f]});f=[];d=RegExp(Layers.markerPrefix);for(e=0;e<c.length;e++){var g=c[e],h=null;if(g.title.match(d))h=f;else{h={name:g.title,parent:g.parent,layers:[]};if(h.parent){var l=f.findIndex(function(a){return a.name==g.parent});-1<l&&f[l].layers.push(h)}else f.push(h);h=h.layers}for(l=0;l<g.layers.length;l++)h.push({name:g.layers[l].layername,layers:[]})}b({groups:c,layertree:f})}};var Gui={signedIn:!1,tracking:!1,following:!0,orientation:!0,initialLoad:!0,selectedLayer:null,draggedLayerIndex:null,layerOrderChanged:!1,updateLayout:function(){$("#map").height(window.innerHeight);$("#map").width(window.innerWidth);$("#panelTopics").height(window.innerHeight-100);$("#panelLayerAll").height(window.innerHeight-100);$("#panelLayerOrder").height(window.innerHeight-100);$("#panelFeatureInfo #featureInfoResults").height(window.innerHeight-80);$("#panelSearch .ui-listview").height(window.innerHeight);
$("#panelPropertiesMap").height(window.innerHeight-100);$("#panelPropertiesEditor").height(window.innerHeight-100)},panelSelect:function(a){$("#panelTopics").toggle("panelTopics"===a);$("#panelLayerAll").toggle("panelLayerAll"===a);$("#panelLayerOrder").toggle("panelLayerOrder"===a);$("#buttonTopics").toggleClass("selected","panelTopics"===a);$("#buttonLayerAll").toggleClass("selected","panelLayerAll"===a);$("#buttonLayerOrder").toggleClass("selected","panelLayerOrder"===a)},propertiesSelect:function(a){$("#panelPropertiesMap").toggle("panelPropertiesMap"===
a);$("#panelPropertiesEditor").toggle("panelPropertiesEditor"===a);$("#buttonPropertiesMap").toggleClass("selected","panelPropertiesMap"===a);$("#buttonPropertiesEditor").toggleClass("selected","panelPropertiesEditor"===a)},showLocationPanel:function(a){if(a){a=2;"degrees"==proj4.defs[Map.userCrs].units&&(a=4);var b=Map.geolocation.getPosition(),c=new ol.geom.Point(b);Map.userCrs!=projectData.crs&&c.transform(projectData.crs,Map.userCrs);var b=Map.geolocation.getAccuracy(),d=Map.geolocation.getAltitude();
"function"==typeof Map.geolocation.getAltitudeCorrected&&(d=Map.geolocation.getAltitudeCorrected());var e=Map.geolocation.getProperties(),f=Map.geolocation.getHeading(),g=Map.geolocation.getSpeed();a=[c.getCoordinates()[0].toFixed(a)+", "+c.getCoordinates()[1].toFixed(a)];Eqwc.settings.mobileShowAccuracy&&("function"==typeof Editor?b<EditorConfig.accuracyLimit?a.push(I18n.geolocation.accuracy+": "+b.toPrecision(3)+" m"):a.push('<span style="color:red;font-weight:bold;">'+I18n.geolocation.accuracy+
": "+b.toPrecision(4)+" m </span>"):a.push(I18n.geolocation.accuracy+": "+b.toPrecision(3)+" m"));d&&(a.push(I18n.geolocation.altitude+": "+d.toFixed(2)+" m"),0<e.altCorrection&&a.push(e.altCorrectionSource),a.push("AH: "+parseFloat(e.antenna-e.antennaOffset)+" m "+e.antennaType));f&&1<g&&(a.push(I18n.geolocation.heading+": "+Math.round(360*f/(2*Math.PI))+"&deg;"),a.push(I18n.geolocation.speed+": "+(3.6*g).toFixed(1)+" km/h"));$("#locationPanel").html(a.join("<br />"));$("#locationPanel").show()}else $("#locationPanel").hide(),
"function"==typeof Editor&&mobGoto&&mobGoto.showGotoPanel(!1)},loadTopics:function(a){var b="",c="";Map.topics={};for(var d=0;d<a.length;d++){for(var e=a[d],f=0;f<e.topics.length;f++){var g=e.topics[f];!1!=g.main_layer&&(b+='<a href="'+Eqwc.settings.gisPortalRoot+'" target="_self"><img class="client-image" src="'+g.icon+'"/></a>');Map.topics[g.name]={title:g.title,wms_url:g.wms_url,background_layer:g.background_layer,overlay_layer:g.overlay_layer,minscale:g.minscale,bg_topic:g.bg_topic,overlay_topics:g.overlay_topics}}c+=
'<div id="topicList" data-role="collapsible">';c+="<h4>"+g.title+"</h4>";c+="<p>"+projectData.project+"</p>";c+="<p>"+projectData.crs+"</p>";"{}"!=projectData.description&&(c+="<p>"+projectData.description+"</p>");c+="</div>"}a=$("#topicMain");a.prepend(c);a.prepend(b);a.find("div[data-role=collapsible]").collapsible({theme:"c",refresh:!0});Gui.selectTopic(Config.permalink.initialTopic||Config.data.initialTopic)},selectTopic:function(a){Map.clearLayers();Map.topic=a;Map.setMinScaleDenom(Map.topics[Map.topic].minscale||
Config.map.minScaleDenom.map);Layers.loadLayers(null,Gui.loadLayers);Gui.loadExtraLayers();Gui.loadBackgroundLayers()},loadLayers:function(a){function b(c,f,g,h){if(0<c.layers.length)d+='<div data-role="collapsible" data-theme="c"',Config.gui.useLayertreeGroupCheckboxes&&(d+=' data-groupcheckbox="true"'),d+=">",d+="<h3>"+c.name+"</h3>";else{var s=f||Layers.markerPrefix+c.name,k=$.grep(a.groups,function(a){return a.title===s})[0];if(void 0!=k){k=$.grep(k.layers,function(a){return a.layername===c.name})[0];
if(-1<Eqwc.common.getHiddenLayersFromSettings().indexOf(k.layername)||"No geometry"==k.geom_type&&(!k.wfs||Eqwc.common.findParentRelation(k.layername)&&projectData.relations.hideJoinField)||Config.baseLayerExists(k.layername)||Config.extraLayerExists(k.layername))return;var p=k.layername;projectData.use_ids&&(p=k.id);"No geometry"==k.geom_type?"function"==typeof Editor&&(d+="<a href=\"javascript:Eqwc.common.callEditor('"+p+'\',null, \'add\');" style="text-align: left;" data-role="button" mini"true" data-theme="c" id="'+
p+'"',d+=' data-icon="plus" data-iconpos="right" data-groupcheckbox="false"',d+=">",d+=c.name+"</a>"):(d+='<div data-role="collapsible" data-theme="c" id="'+p+'"',d+=' data-iconpos="right" data-collapsed-icon="arrow-r" data-expanded-icon="arrow-d" data-groupcheckbox="true"',d+=">",d+="<h3>"+c.name+"</h3>");d+='<label style="display:none">';d+='<input style="display:none" type="'+h+'" ';null!=f&&(d+='data-role="none" ');d+='name="'+k.layername+'" ';d+='data-layer="'+p+'" ';k.visini&&(d+="checked ");
d+=">"+k.toclayertitle;d+="</input>";d+="</label>";d+="</div>";e.push({id:p,layername:k.layername,title:k.toclayertitle,wms_sort:k.wms_sort,visible:k.visini,minscale:k.minscale,maxscale:k.maxscale,hidden_attributes:k.hidden_attributes,hidden_values:k.hidden_values,identify:!!k.identify,geom_type:k.geom_type})}}for(f=0;f<c.layers.length;f++)b(c.layers[f],c.name,g+1,"checkbox");0<c.layers.length&&(d+="</div>")}function c(){if(""==this.id){var a=$(this).children(".ui-collapsible-content").children("label");
a.find(':checkbox[data-role="none"]').attr("data-role",null);a.trigger("create")}else{var a=this.id,b=projectData.layers[a];b&&"gdal"!==b.provider&&"wms"!==b.provider&&(b=Map.topics[Map.topic].wms_url+"?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphics&FORMAT=image/png&EXCEPTIONS=application/vnd.ogc.se_inimage&BOXSPACE=1&LAYERSPACE=2&SYMBOLSPACE=1&SYMBOLHEIGHT=2&LAYERFONTSIZE=8&ITEMFONTSIZE=8&ICONLABELSPACE=2&LAYERTITLE=FALSE&LAYERTITLESPACE=0&TRANSPARENT=TRUE&LAYERS="+encodeURIComponent(a)+"&RULELABEL=AUTO&DPI="+
encodeURIComponent(Config.map.dpi),a='<img data-layer="'+a+'" src="'+b+'"</img>',$(this).children(".ui-collapsible-content").append(a))}$(this).unbind("expand",c)}for(var d="",e=[],f=0;f<a.layertree.length;f++)b(a.layertree[f],null,0,"checkbox");$("#panelLayerAll").html(d);$("#panelLayerAll").trigger("create");$("#panelLayerAll").find(".ui-collapsible").bind("expand",c);$("#panelLayerAll").children(".ui-collapsible[data-groupcheckbox=true]").bind("groupchange",function(a){var b=Map.visibleLayers();
$(this).find(":checkbox").each(function(a){-1!=b.indexOf($(this).data("layer"))!=$(this).is(":checked")&&(Map.setLayerVisible($(this).data("layer"),$(this).is(":checked"),!1),Gui.updateLayerOrder($(this).data("layer"),$(this).is(":checked")))})});e=e.sort(function(a,b){return a.wms_sort-b.wms_sort});Map.layers={};for(f=0;f<e.length;f++){var g=e[f];Map.layers[g.id]={id:g.id,title:g.title,visible:g.visible,wms_sort:g.wms_sort,minscale:g.minscale,maxscale:g.maxscale,hidden_attributes:g.hidden_attributes,
hidden_values:g.hidden_values,transparency:0,identify:g.identify,geom_type:g.geom_type}}Gui.layerOrderChanged=!1;Gui.initialLoad&&Gui.applyPermalink();Map.setTopicLayer();Gui.resetLayerOrder();g=Map.topics[Map.topic].overlay_topics||[];if(Gui.initialLoad&&null!=Config.permalink.initialOverlayTopics)for(f=0;f<Config.permalink.initialOverlayTopics.length;f++){var h=Config.permalink.initialOverlayTopics[f];-1==g.indexOf(h)&&g.push(h)}Gui.setupOverlayTopics(g);Config.permalink.addOverlays(Gui.setSelectionLayer,
Gui.setRedliningLayer);Gui.initialLoad&&(Gui.initialLoad=!1);$.event.trigger({type:"topiclayersloaded",topic:Map.topic})},loadBackgroundLayers:function(a){if(0!=Config.data.baselayers.length){a='<div data-role="collapsible" data-theme="c">'+("<h3>"+I18n.layers.background+"</h3>");for(var b=0;b<Config.data.baselayers.length;b++){var c=Config.data.baselayers[b],d="";0==b&&Eqwc.settings.visibleFirstBaseLayer&&(d=' checked="checked"');a+='<label><input type="checkbox" name="_background_" id="'+c.name+
'" data-background="true"'+d+">"+c.title+"</label>";Map.setBackgroundLayer(c.name,b,!0)}a+="</div>";$("#panelLayerAll").append(a);$("#panelLayerAll").trigger("create");$("#panelLayerAll :checkbox[data-background=true]").on("change",function(a){a=$(this).attr("id");a=Map.backgroundLayers[a];var b=$(this).is(":checked");Gui.toggleBackgroundLayer(a,b)});null!=Config.permalink.initialBackgroundTopic&&(a=Config.getBaseLayerName(Config.permalink.initialBackgroundTopic))&&($("input#"+a).prop("checked",!0).checkboxradio("refresh"),
Gui.toggleBackgroundLayer(Map.backgroundLayers[a],!0))}},loadExtraLayers:function(a){if(void 0!=Config.data.extralayers){a='<div data-role="collapsible" data-theme="c">'+("<h3>"+I18n.layers.overlays+"</h3>");for(var b=0;b<Config.data.extralayers.length;b++){var c=Config.data.extralayers[b],d="";$.parseJSON(c.definition).visibility&&(d=' checked="checked"');a+='<label><input type="checkbox" name="_extra_" id="'+c.name+'" data-extra="true"'+d+">"+c.title+"</label>";Map.setBackgroundLayer(c.name,b,!1)}a+=
"</div>";$("#panelLayerAll").append(a);$("#panelLayerAll").trigger("create");$("#panelLayerAll :checkbox[data-extra=true]").bind("change",function(a){a=$(this).attr("id");a=Map.backgroundLayers[a];var b=$(this).is(":checked");a.setVisible(b)})}},setupOverlayTopics:function(a){a=$.grep(a,function(a,b){return void 0!=Map.topics[a]&&Map.topics[a].overlay_layer});Map.clearOverlayLayers();$("#overlayTopics").remove();if(0<a.length){var b;b='<div id="overlayTopics" data-role="collapsible" data-theme="c" data-groupcheckbox="false">'+
("<h3>"+I18n.layers.overlays+"</h3>");for(var c=a.length-1;0<=c;c--){var d=a[c];b+="<label>";b+='<input type="checkbox" ';b+='name="overlayTopic_'+d+'" ';b+='data-overlay_topic="'+d+'" ';b+="checked";b+=">"+Map.topics[d].title;b+="</label>"}b+="</div>";$("#panelLayerAll").append(b);$("#panelLayerAll").trigger("create");for(c=0;c<a.length;c++)Gui.addOverlayTopicLayer(a[c]);$("#panelLayerAll :checkbox[data-overlay_topic]").bind("change",function(a){Map.toggleOverlayLayer($(this).data("overlay_topic"),
$(this).is(":checked"))})}},addOverlayTopicLayer:function(a){Layers.loadLayers(Config.data.layersUrl(a),function(b){var c=b.groups;b=[];for(var d=0;d<c.length;d++)for(var e=c[d],f=0;f<e.layers.length;f++){var g=e.layers[f];g.visini&&b.push({layername:g.layername,wms_sort:g.wms_sort})}b=b.sort(function(a,b){return a.wms_sort-b.wms_sort});c=[];for(d=0;d<b.length;d++)c.push(b[d].layername);Map.addOverlayLayer(a,c)})},setSelectionLayer:function(a){if(null!=a){var b='<label><input type="checkbox" name="_selection_" data-selection="true" checked>'+
I18n.layers.selection+"</label>";$("#panelLayerAll").append(b);$("#panelLayerAll").trigger("create");$("#panelLayerAll :checkbox[data-selection=true]").bind("change",function(a){Map.toggleSelectionLayer($(this).is(":checked"))})}else $("#panelLayerAll :checkbox[data-selection=true]").parent(".ui-checkbox:first").remove();Map.setSelectionLayer(a)},setRedliningLayer:function(a){if(null!=a){var b='<label><input type="checkbox" name="_redlining_" data-redlining="true" checked>'+I18n.layers.redlining+
"</label>";$("#panelLayerAll").append(b);$("#panelLayerAll").trigger("create");$("#panelLayerAll :checkbox[data-redlining=true]").bind("change",function(a){Map.toggleRedliningLayer($(this).is(":checked"))})}else $("#panelLayerAll :checkbox[data-redlining=true]").parent(".ui-checkbox:first").remove();Map.setRedliningLayer(a)},resetLayerOrder:function(){var a="",b;for(b in Map.layers)Map.layers[b].visible&&(a='<li data-layer="'+b+'" data-wms_sort="'+Map.layers[b].wms_sort+'">'+Map.layers[b].title+"</li>"+
a);$("#listOrder").html(a);$("#listOrder").listview("refresh");Gui.selectLayer(null)},updateLayerOrder:function(a,b){if(b){var c='<li data-layer="'+a+'" data-wms_sort="'+Map.layers[a].wms_sort+'">'+Map.layers[a].title+"</li>";if(Gui.layerOrderChanged)$("#listOrder").prepend(c);else{var d=$("#listOrder li").filter(function(){return $(this).data("wms_sort")<Map.layers[a].wms_sort}).first();0<d.length?d.before(c):(d=$("#listOrder li").filter(function(){return $(this).data("wms_sort")>Map.layers[a].wms_sort}).last(),
0<d.length?d.after(c):$("#listOrder").prepend(c))}}else $('#listOrder li[data-layer="'+a+'"]').remove();$("#listOrder").listview("refresh");Gui.onLayerOrderChanged(null,null)},onLayerDrag:function(a,b){Gui.draggedLayerIndex=$("#listOrder li").index(b.item)},onLayerOrderChanged:function(a,b){null!=b&&$("#listOrder li").index(b.item)!=Gui.draggedLayerIndex&&(Gui.layerOrderChanged=!0);Gui.selectLayer(null);var c={};$($("#listOrder li").get().reverse()).each(function(a){a=$(this).data("layer");c[a]=Map.layers[a]});
for(var d in Map.layers)void 0===c[d]&&(c[d]=Map.layers[d]);Map.layers=c;setTimeout(function(){Map.refresh()},1E3)},selectLayer:function(a){$("#listOrder li").removeClass("selected");Gui.selectedLayer=a;null!=Gui.selectedLayer?($('#listOrder li[data-layer="'+a+'"]').addClass("selected"),$("#sliderTransparency").val(Map.layers[a].transparency).slider("refresh"),$("#sliderTransparency").slider("enable")):($("#sliderTransparency").val(0).slider("refresh"),$("#sliderTransparency").slider("disable"))},
showFeatureInfoResults:function(a,b,c){"success"==a?"text/xml"===Config.featureInfo.format?Gui.showXMLFeatureInfoResults(b):$("#featureInfoResults").html(b.join("")):401===c?Eqwc.common.redirect():(a=Gui.addFeatureInfoTopButtons(),$("#featureInfoResults").html(a),$("#featureInfoResults").trigger("create"));$("#panelFeatureInfo").panel("open");Map.toggleClickMarker(!0)},addFeatureInfoTopButtons:function(){var a;a=""+('<a href="javascript:Map.openNavigation();" data-theme="e" data-inline="true" data-mini="true" data-role="button">'+
TR.navigation+"</a>");"function"==typeof Editor&&mobEditor&&mobEditor.layer&&(a+='<a href="javascript:mobEditor.addPointOnClickPos();" data-theme="a" data-inline="true" data-mini="true" data-role="button">'+TR.editAdd+"</a>",EditorConfig.useOffset&&(a+='<a href="javascript:mobEditor.startOffset();" data-theme="a" data-inline="true" data-mini="true" data-role="button">'+TR.editAddOffset+"</a>"));return a},showXMLFeatureInfoResults:function(a){for(var b=Eqwc.settings.qgisFilesFieldAlias?Eqwc.settings.qgisFilesFieldAlias:
"files",b=b.toUpperCase(),c=Gui.addFeatureInfoTopButtons(),d=0;d<a.length;d++){var e=a[d],f=Map.layers[e.layer],g=0,h=Config.getLayerName(e.layer),h=Eqwc.common.getIdentifyLayerNameRevert(h),l=Eqwc.common.getLayerId(h);void 0==f&&(f=Map.layers[l]);h=e.layer;void 0!=f?h=f.title:(f=projectData.layers[l],h=f.layername);projectData.relations&&projectData.relations[h]&&(g=projectData.relations[h].length);c+='<div data-role="collapsible" data-collapsed="false" data-theme="c">';c+="<h3>"+h+" ("+e.features.length+
")</h3>";void 0==f&&(f=projectData.layers[e.layer]);for(l=0;l<e.features.length;l++){var r=e.features[l],n=null===r.id?I18n.featureInfo.raster:I18n.featureInfo.feature+r.id,c=c+'<div class="feature" data-role="collapsible" data-collapsed="false" data-theme="c">',c=c+("<h3>"+n+"</h3>"),n=!1;"function"==typeof Editor&&"No geometry"!=f.geom_type&&(n=!0,c+='<div data-role="controlgroup" data-type="horizontal" data-mini="true">',Config.data.wfslayers[f.id]&&(c+="<a href=\"javascript:Eqwc.common.callEditor('"+
f.id+"',"+r.id+', \'edit\');" data-theme="b" data-role="button">'+TR.editEdit+"</a>"),Config.data.gotolayers[f.id]&&(c+="<a href=\"javascript:Eqwc.common.callEditor('"+f.id+"',"+r.id+', \'goto\');" data-theme="e" data-role="button">'+I18n.editor.goto+"</a>"));if(0<g){var m=Eqwc.common.getLayerId(projectData.relations[h][0].relate_layer),s=projectData.relations[h][0].join_field;n||(n=!0,c+='<div data-role="controlgroup" data-type="horizontal" data-mini="true">');c+="<a href=\"javascript:Gui.wmsSearch('"+
m+"','"+r.id+"', '"+s+'\');" data-role="button" data-iconpos="notext" data-icon="bars" data-theme="b">'+TR.relations+"</a>";1==g&&"function"==typeof Editor&&Config.data.wfslayers[m]&&"No geometry"==projectData.layers[m].geom_type&&(c+="<a href=\"javascript:Eqwc.common.callEditor('"+m+"','"+r.id+"', 'addRelation', '"+s+'\');" data-role="button" data-iconpos="notext" data-icon="plus" data-theme="a">'+TR.editAdd+"</a>")}n&&(c+="</div>");c+='<ul class="ui-listview-inset ui-corner-all" data-role="listview">';
for(n=0;n<r.attributes.length;n++){var m=r.attributes[n],k=s=m.name.toUpperCase(),c=c+"<li>";if(s==b){if(""<m.value){var p=$.parseJSON(m.value),t=[];if(null===p)m.value=Eqwc.settings.noDataValue;else{for(var q=0;q<p.length;q++)t.push(Eqwc.common.manageFile(p[q],!0));m.value=t.join("</br>")}}}else Eqwc.settings.fieldTemplates&&Eqwc.settings.fieldTemplates.hasOwnProperty(s)?(p=Eqwc.settings.fieldTemplates[s],p.newName&&(k=p.newName),""<m.value&&(t=s+"___"+m.value,p.url&&!1===Eqwc.tooltips.hasOwnProperty(t)&&
(Eqwc.tooltips[t]=null),q=m.value,p.template&&(q=p.template.replaceAll("%VALUE%",m.value),q=q.replaceAll("%PROJECT%",projectData.project)),p.url&&(q='<a href="#tooltip_'+t+'" id="open_'+t+'" data-rel="popup" data-inline="true" data-transition="pop" data-position-to="window">'+m.value+"</a>",q+='<div data-role="popup" id="tooltip_'+t+'" data-overlay-theme="a">',q+='<p id="'+t+'">...</p>',q+="</div>"),m.value=q)):m.value=Eqwc.common.createHyperlink(m.value,null,null),"true"===m.value&&(m.value=TR.trueText),
"false"===m.value&&(m.value=TR.falseText);"MAPTIP"!==s&&s!==b&&-1==s.indexOf("LGS_IMG")&&(c+='<span class="name">'+k+": </span>");c+='<span class="value">'+m.value+"</span>";c+="</li>"}c+="</ul>";c+="</div>"}c+="</div>"}0==a.length&&(c+="</br>"+I18n.featureInfo.noFeatureFound);$("#featureInfoResults").html(c);$("#featureInfoResults").on("create",function(){$.each(Eqwc.tooltips,function(a){var b=a.split("___"),c=b[0],d=b[1];$("#open_"+a).on("click",function(){$.ajax({url:Eqwc.settings.fieldTemplates[c].url+
d,type:"GET",success:function(b){""==b&&(b=Eqwc.settings.toolTipEmptyText?Eqwc.settings.toolTipEmptyText:"no data");$("#"+a).html(b);Eqwc.tooltips[a]=b}})})})});$("#featureInfoResults").trigger("create")},showSearchResults:function(a){$("#searchResultsList").empty();for(var b=0;b<a.length;b++){var c=a[b];null!=c.category&&$("#searchResultsList").append($('<li class="category-title">'+c.category+"</li>"));for(var d=0;d<c.results.length;d++){var e=c.results[d],f=$('<li><a href="#">'+e.name+"</a></li>");
f.data("bbox",e.bbox);f.data("highlight",e.highlight);f.data("point",e.point);$("#searchResultsList").append(f)}}$("#searchResultsList").listview("refresh");$("#searchResults").show()},jumpToSearchResult:function(a){Map.searchMarker.setPosition(a.getCoordinates());Map.zoomToExtent(a.getExtent(),Config.map.minScaleDenom.search);Map.toggleFollowing(!1);$("#panelSearch").panel("close")}};
$(document).bind("pageinit",function(){$("#listOrder").sortable();$("#listOrder").bind("sortstart",Gui.onLayerDrag);$("#listOrder").bind("sortstop",Gui.onLayerOrderChanged)});
Gui.updateTranslations=function(){var a=projectData.title;document.title=Eqwc.settings.gisPortalTitle?a+" | "+Eqwc.settings.gisPortalTitle:a;$("#panelSearch b").html(I18n.search.header);$("#panelSearch #searchResults b").html(I18n.search.results);$("#panelProperties #buttonPropertiesMap .ui-btn-text").html(I18n.properties.header);$("#panelProperties label[for=switchOrientation]").html(I18n.properties.mapRotation);$("#panelProperties label[for=switchScale]").html(I18n.properties.scaleBar);$("#panelProperties .ui-slider-label:contains(Ein)").html(I18n.properties.on);
$("#panelProperties .ui-slider-label:contains(Aus)").html(I18n.properties.off);$("#panelProperties #buttonLogo .ui-btn-text").html(I18n.properties.about);$("#dlgAbout h1").html(I18n.about.header);$("#panelProperties #buttonShare .ui-btn-text").html(I18n.properties.share);$("#panelProperties #buttonLogin .ui-btn-text").html(I18n.properties.login);$("#panelProperties #buttonLoginSSL .ui-btn-text").html(I18n.properties.login);$("#dlgLogin h1").html(I18n.login.header);$("#dlgLogin label[for=user]").html(I18n.login.user);
$("#dlgLogin label[for=password]").html(I18n.login.password);$("#dlgLogin #buttonSignIn .ui-btn-text").html(I18n.login.signIn);$("#dlgLogin #buttonLoginCancel .ui-btn-text").html(I18n.login.cancel);$("#panelProperties #buttonSignOut .ui-btn-text").html(I18n.login.signOut);$("#panelLayer #buttonTopics .ui-btn-text").html(I18n.layers.project);$("#panelLayer #buttonLayerAll .ui-btn-text").html(I18n.layers.layers);$("#panelLayer #buttonLayerOrder .ui-btn-text").html(I18n.layers.layerOrder);$("#panelLayer #sliderTransparency-label").html(I18n.layers.transparency);
$("#panelFeatureInfo b").html(I18n.featureInfo.header);$("#measurePanel label[for=measureArea]").html(I18n.measureArea);$("#measurePanel .ui-slider-label:contains(Ein)").html(I18n.properties.on);$("#measurePanel .ui-slider-label:contains(Aus)").html(I18n.properties.off)};Gui.toggleOrientation=function(a){Gui.orientation=a;Map.toggleOrientation(Gui.orientation)};
Gui.applyPermalink=function(){null!=Config.permalink.startExtent?Map.zoomToExtent(Config.permalink.startExtent,null):(null!=Config.permalink.startCenter&&Map.setCenter(Config.permalink.startCenter),null!=Config.permalink.startScale?Map.setScale(Config.permalink.startScale):null!=Config.permalink.startZoom&&Map.setZoom(Config.permalink.startZoom));var a=function(a,b){Map.layers[a].visible=b;var c=$('#panelLayerAll :checkbox[data-layer="'+a+'"]');c.is(":checked")!=b&&c.prop("checked",b)};if(null!=Config.permalink.activeLayers){var b=
[],c=!1,d=-1,e;for(e in Map.layers){var f=$.inArray(e,Config.permalink.activeLayers),g=-1!=f;a(e,g);g&&(b.push({layername:e,sort:f}),c||(c=f<d,d=f))}b=b.sort(function(a,b){return a.sort-b.sort});a={};for(d=0;d<b.length;d++)e=b[d].layername,a[e]=Map.layers[e];for(e in Map.layers)void 0===a[e]&&(a[e]=Map.layers[e]);Map.layers=a;Gui.layerOrderChanged=c}else if(null!=Config.permalink.inactiveLayers)for(e in Map.layers)f=$.inArray(e,Config.permalink.inactiveLayers),-1!=f&&a(e,!1);if(null!=Config.permalink.opacities)for(e in Config.permalink.opacities)void 0!=
Map.layers[e]&&(b=Math.round((255-Config.permalink.opacities[e])/255*100),Map.layers[e].transparency=b)};Gui.loginStatus=function(a){a.success=!0;a.user=projectData.user;a.success&&($("#dlgLogin").popup("close"),Eqwc.settings.useGisPortal?$("#buttonSignOut .ui-btn-text").html(a.user):$("#buttonSignOut .ui-btn-text").html(I18n.login.signOut+" - "+a.user),$("#panelProperties").panel("close"));Gui.toggleLogin(a.success)};
Gui.login=function(a){a.success?(Topics.loadTopics(null,Gui.loadTopics),$("#dlgLogin").popup("close"),Eqwc.settings.useGisPortal?$("#buttonSignOut .ui-btn-text").html(a.user):$("#buttonSignOut .ui-btn-text").html(I18n.login.signOut+" - "+a.user),Gui.toggleLogin(!0),$("#panelProperties").panel("close")):alert(I18n.login.signInFailed)};Gui.logout=function(){$("#panelProperties").panel("close");window.location.href=Eqwc.settings.useGisPortal?Eqwc.settings.gisPortalProfile:"./admin/login.php?action=logout"};
Gui.toggleLogin=function(a){Gui.signedIn=a;$("#buttonLogin").toggle(!a);$("#buttonSignOut").toggle(a)};Gui.fillMapCrs=function(){$.each(Config.map.projectionList,function(a,b){$("#mapCrs").append($("<option>",{value:b[0],text:b[1]}))});$("#mapCrs").on("change",function(){Map.userCrs=this.value;$("#locationPanel").is(":visible")&&Map.geolocation&&Gui.showLocationPanel(!0)});$("#mapCrs").val(projectData.crs).change()};
Gui.wmsSearch=function(a,b,c){b=a+':"'+c+"\" = '"+b+"'";(new FeatureInfo(Gui.showFeatureInfoResults)).filter(b,a)};Gui.showBookmark=function(){var a=this.id.split("_")[1],b=JSON.parse(projectData.bookmarks)[a],a=b[2],b=b[4],a=(new ol.format.WKT).readGeometry(a,{dataProjection:b,featureProjection:projectData.crs});Map.zoomToExtent(a.getExtent())};
Gui.loadBookmarks=function(){function a(a,b){var c=a[0],d="bmId_"+JSON.parse(projectData.bookmarks).findIndex(function(b){return b[3]==a[3]});$("#bmGroup_"+b).append('<li id="'+d+'"><a href="#">'+c+"</a></li>").listview("refresh");$("#"+d).click(Gui.showBookmark)}var b=$("#topicMain"),c=JSON.parse(projectData.bookmarks);if(0!=c.length){var d=[],e;e='<div data-role="collapsible">'+("<h4>"+TR.bookmarks+"</h4>");e+='<form id="makecollapsible"></form>';e+="</div>";b.append(e).trigger("create");$("#makecollapsible").append($("<div>").attr({"data-role":"collapsible-set",
id:"bookmarkList"}));$("#makecollapsible").collapsibleset().trigger("create");$.each(c,function(b,c){var e=c[1];""==e&&(e=TR.bookmarkEmptyGroupText,c[1]=e);var l=e.replace(/[^a-z0-9\s]/gi,"").replace(/[_\s]/g,"-");-1==d.indexOf(l)&&($("<div>").attr({"data-role":"collapsible"}).html("<h4>"+e+'</h4><ul id="bmGroup_'+l+'" data-role="listview" data-inset="true"></ul>').appendTo("#bookmarkList"),$("#makecollapsible").collapsibleset().trigger("create"),d.push(l));a(c,l)})}};
Gui.toggleBackgroundLayer=function(a,b){a.setVisible(b);var c="input#"+a.name;$("#panelLayerAll :checkbox[data-background=true]").not($(c)).prop("checked",!1).checkboxradio("refresh");for(c=0;c<Config.data.baselayers.length;c++){var d=Config.data.baselayers[c].name;d!==a.name&&Map.backgroundLayers[d].setVisible(!1)}};Gui.closeGuestWin=function(){$.mobile.changePage($("#mappage"))};
Gui.showGuestWin=function(){var a=$("<div data-role='page' data-theme='c' data-close-btn='none' id='guestWinPage'><div data-role='content' style='padding:10px;' data-theme='c'>"+Eqwc.settings.guestWinText+"</div><div data-position='fixed' class='ui-bar-a ui-footer-fixed slideup'><a href='#' data-theme='c' data-inline='true' data-role='button' id='guestWinConfirm'>"+Eqwc.settings.guestWinConfirm+"</a></div></div>");a.appendTo($.mobile.pageContainer);$("#guestWinConfirm").click($.proxy(Gui.closeGuestWin,
this));$.mobile.changePage(a)};
Gui.initViewer=function(){Gui.updateTranslations();Gui.fillMapCrs();Gui.updateLayout();$(window).on("resize",function(){Gui.updateLayout()});Map.setWindowOrientation(window.orientation);$(window).on("orientationchange",function(a){Map.setWindowOrientation(window.orientation)});Map.createMap();Gui.updateLayout();$("#buttonTopics").on("tap",function(){Gui.panelSelect("panelTopics")});$("#buttonLayerAll").on("tap",function(){Gui.panelSelect("panelLayerAll")});$("#buttonLayerOrder").on("tap",function(){Gui.panelSelect("panelLayerOrder")});
$("#buttonPropertiesMap").on("tap",function(){Gui.propertiesSelect("panelPropertiesMap")});$("#buttonPropertiesEditor").on("tap",function(){Gui.propertiesSelect("panelPropertiesEditor")});$("#switchOrientation").val(Config.defaultProperties.orientation?"on":"off");$("#switchOrientation").slider("refresh");Gui.toggleOrientation(Config.defaultProperties.orientation);$("#switchScale").val(Config.defaultProperties.scalebar?"on":"off");$("#switchScale").slider("refresh");Map.toggleScalebar(Config.defaultProperties.scalebar);
Topics.loadTopics(null,Gui.loadTopics);$("#topicList").delegate("li.topic","vclick",function(a){Gui.selectTopic($(this).data("topic"));$("#panelLayer").panel("close")});Gui.loadBookmarks();$("#panelLayerAll").delegate(":checkbox[data-layer]","change",function(a){a=projectData.use_ids?$(this).data("layer"):projectData.layers[$(this).data("layer")].layername;-1!=Map.visibleLayers().indexOf(a)!=$(this).is(":checked")&&(Map.setLayerVisible($(this).data("layer"),$(this).is(":checked"),!1),Gui.updateLayerOrder($(this).data("layer"),
$(this).is(":checked")))});Gui.panelSelect("panelLayerAll");Gui.propertiesSelect("panelPropertiesMap");$("#listOrder").delegate("li","vclick",function(){Gui.selectLayer($(this).data("layer"))});$("#sliderTransparency").on("slidestop",function(){Map.setLayerTransparency(Gui.selectedLayer,$(this).val(),!0)}).parent().on("swipeleft",function(a,b){a.stopPropagation()});$(document).on("maprotation",function(a){$("#btnCompass").find(".ui-icon").css("transform","rotate("+a.rotation+"rad)");$("#btnCompass").fadeIn()});
$("#btnCompass").on("tap",function(){Map.setRotation(0);$("#btnCompass").fadeOut()});projectData.geolocation||$("#btnLocation").hide();$("#locationPanel").hide();$("#btnInfo").hide();$("#gotoPanel").hide();$("#editPanel").hide();$("#recordPanel").hide();$("#btnLocation").on("tap",function(){Gui.tracking?Gui.following?($("#btnLocation .ui-icon").toggleClass("ui-icon-location_on",!1),$("#btnLocation .ui-icon").toggleClass("ui-icon-location_off",!0),Map.toggleTracking(!1),Gui.tracking=!1):($("#btnLocation .ui-icon").toggleClass("ui-icon-location_out",
!1),$("#btnLocation .ui-icon").toggleClass("ui-icon-location_on",!0),Map.centerOnLocation(),Map.toggleFollowing(!0)):($("#btnLocation .ui-icon").toggleClass("ui-icon-location_off",!1),$("#btnLocation .ui-icon").toggleClass("ui-icon-location_on",!0),Map.toggleTracking(!0),Gui.tracking=!0,Map.toggleFollowing(!0),$("#locationPanel").html(I18n.geolocation.obtaining),$("#locationPanel").show())});$("#btnInfo").click(Map.featureInfoOnLocation);var a=new FeatureInfo(Gui.showFeatureInfoResults);Map.registerClickHandler("featureInfo",
a);Map.activateClickHandler("featureInfo");$("#panelFeatureInfo").on("panelclose",function(){Map.toggleClickMarker(!1)});$("#featureInfoResults").parent().on("swipeleft",function(a,b){a.stopPropagation()});Config.search||$("#btnSearching").addClass("ui-disabled");var b=function(){$("#searchResults").hide();Map.setHighlightLayer(null);Map.searchMarker.setPosition(void 0)};$("#searchInput").bind("change",function(a){""==$(this).val()&&b()});$("#searchForm").bind("submit",function(a){b();var c=$("#searchInput").val();
""!=c&&(Config.search.submit(c,Gui.showSearchResults),$("#searchInput").blur());a.preventDefault();a.stopPropagation()});$("#searchResultsList").delegate("li","vclick",function(){null!=$(this).data("point")&&Gui.jumpToSearchResult($(this).data("point"));void 0!=$(this).data("highlight")&&Config.search.highlight($(this).data("highlight"),Map.setHighlightLayer)});$("#btnAlert").click(function(){var a=[];$.each(Map.alertMessages,function(b,c){a.push(b+": "+c)});0<a.length&&alert(a.join("\n"))});$("#btnMeasure").click(Map.startMeasuring);
$("#btnMeasureFinish").click(function(){Map.finishMeasuringSketch()});$("#btnMeasureRemove").click(function(){Map.removeLastMeasurePoint()});$("#btnMeasureStop").click(function(){Map.stopMeasuring()});$("#measureArea").on("change",function(a){Map.map.removeInteraction(Map.measurementSketch);Map.startMeasuring()});$("#switchOrientation").on("change",function(a){Gui.toggleOrientation("on"==$(this).val())}).parent().on("swiperight",function(a,b){a.stopPropagation()});$("#switchScale").on("change",function(a){Map.toggleScalebar("on"==
$(this).val())}).parent().on("swiperight",function(a,b){a.stopPropagation()});$("#aboutContent").html(I18n.about.content);$("#buttonShare").toggle(!Config.gui.hideShareButton);$("#buttonLogin").toggle(!Config.gui.hideLoginButton);$("#buttonLoginSSL").hide();$("#buttonSignOut").hide();if(!Config.gui.hideLoginButton)if(Config.sslLogin&&!UrlParams.useSSL){var a=UrlParams.baseUrl.replace(/^http:/,"https:"),c=$.extend({openLogin:!0},UrlParams.params),a=a+("?"+$.param(c));$("#buttonLoginSSL").attr("href",
a);$("#buttonLoginSSL").show();$("#buttonLogin").hide()}else $("#buttonSignIn").on("tap",function(){Config.login.signIn($("#user").val(),$("#password").val(),Gui.login)}),$("#buttonLoginCancel").on("tap",function(){$("#dlgLogin").popup("close")}),$("#buttonSignOut").on("tap",function(){Config.login.signOut(Gui.logout)}),Config.login.status(Gui.loginStatus);$("#panelFeatureInfo, #panelLayer, #panelSearch").on("panelopen",function(){Map.toggleClickHandling(!1)});$("#panelFeatureInfo, #panelLayer, #panelSearch").on("panelclose",
function(){Map.measurementActive||Map.toggleClickHandling(!0)});Map.searchMarker=new ol.Overlay({element:$('<div id="searchMarker"></div>')[0],positioning:"center-center",stopEvent:!1});Map.map.addOverlay(Map.searchMarker);Map.loadHiddenIcons();"guest"==projectData.user&&Eqwc.settings.guestWinTitle&&Gui.showGuestWin();Config.customInitViewer()};
$(document).ready(function(a){$.mobile.loader.prototype.defaultHtml="<div class='ui-loader'><span class='ui-icon ui-icon-loading'></span><h1></h1><div class='ui-loader-curtain'></div></div>";UrlParams.parse();Config.permalink.read(UrlParams.params,Gui.initViewer)});
